
export default {
    title: 'xxxx检查化验单',
    name: '张三',
    levelText: '普通会员',
    cellPhone: '185xxxxxxxx',
    sexText: '男',
    birthdate:'2000-01-01',
    petName: '宠物名称',
    petGenderText: '公',
    petBirthDate:'2000-01-01',
    petKindText:'宠物种类',
    petVarietieText:'宠物品种',
    petColorText:'宠物颜色',
    petWeight:'0.00Kg',
    petRecordNumber:'R0000000001',
    allName:'',
    testItemDetails: [
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
        { orderName:'分组1',itemName: '测试商品01', unitName: '盒', salePrice: '20', count: '2',amountPrice:'40.00',remark:"备注" },
    ],
};