/* tslint:disable */
/* eslint-disable */
/**
 * 病例相关打印
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * <br />&nbsp;化验单模板 Test = 1001<br />&nbsp;处方笺模板 Prescription = 1002<br />&nbsp;驱虫/疫苗模板 Prevent = 1003<br />&nbsp;收费清单模板 FeeList = 1004<br />&nbsp;麻醉单模板 Anesthesia = 1005<br />&nbsp;化验结果单 TestResult = 2001<br />&nbsp;A4账单 BillA4 = 2004<br />&nbsp;诊疗模板 RecordA4 = 3001<br />&nbsp;超声检查模板 Bscan = 4001<br />&nbsp;摄影检查模板 XRay = 5001<br />&nbsp;显微镜模板 Micro = 6001<br />&nbsp;试纸结果模板 A4 Paper = 7001<br />&nbsp;小票打印模板 80mm Receipt80 = 8001<br />
 * @export
 * @enum {string}
 */
export enum PrintTempType {
    NUMBER_1001 = 1001,
    NUMBER_1002 = 1002,
    NUMBER_1003 = 1003,
    NUMBER_1004 = 1004,
    NUMBER_1005 = 1005,
    NUMBER_2001 = 2001,
    NUMBER_2004 = 2004,
    NUMBER_3001 = 3001,
    NUMBER_4001 = 4001,
    NUMBER_5001 = 5001,
    NUMBER_6001 = 6001,
    NUMBER_7001 = 7001,
    NUMBER_8001 = 8001
}

