/* tslint:disable */
/* eslint-disable */
/**
 * 病例相关打印
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 打印类型枚举<br />&nbsp;
 * 浏览器打印 Browser = 1<br />&nbsp;
 * 客户端打印 Client = 2<br />&nbsp;
 * 化验模板 Test = 1001<br />&nbsp;
 * 处方签 Prescription = 1002<br />&nbsp;
 * 驱虫/疫苗模板 Prevent = 1003<br />&nbsp;
 * 收费清单模板 = 1004<br />
 * 麻醉单模板 = 1005<br />
 * 化验结果单 = 2001<br />
 * A4账单 BillA4 = 2004<br />
 * 超声检查模板 = 4001<br />
 * 摄影检查模板 = 5001<br />
 * 显微镜模板 = 6001<br />
 * 试纸结果模板 A4 = 7001<br />
 * 小票打印模板 80mm = 8001<br />
 * @export
 * @enum {string}
 */
export enum PrintTypeEnum {
    /**
     * 浏览器打印
     */
    NUMBER_1 = 1,
    /**
     * 客户端打印
     */
    NUMBER_2 = 2,
    /**
     * 驱虫/疫苗模板
     */
    NUMBER_1001 = 1001,
    /**
     * 化验模板
     */
    NUMBER_1002 = 1002,
    /**
     * 处方签模板
     */
    NUMBER_1003 = 1003,
    /**
     * 收费清单模板
     */
    NUMBER_1004 = 1004,
    /**
     * 麻醉单模板
     */
    NUMBER_1005 = 1005,
    /**
     * 化验结果单
     */
    NUMBER_2001 = 2001,
    /**
     * A4账单
     */
    NUMBER_2004 = 2004,
    /**
     * 诊疗模板
     */
    NUMBER_3001 = 3001,
    /**
     * 超声检查模板
     */
    NUMBER_4001 = 4001,
    /**
     * 摄影检查模板
     */
    NUMBER_5001 = 5001,
    /**
     * 显微镜模板
     */
    NUMBER_6001 = 6001,
    /**
     * 试纸结果模板 A4
     */
    NUMBER_7001 = 7001,
    /**
     * 小票打印模板 80mm
     */
    NUMBER_8001 = 8001,
}

