/* tslint:disable */
/* eslint-disable */
/**
 * 病例相关打印
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 打印化验明细集合
 *
 * @export
 * @interface PrintTestItemDto
 */
export interface PrintTestItemDto {

    /**
     * 项目名称
     *
     * @type {string}
     * @memberof PrintTestItemDto
     */
    name?: string | null;

    /**
     * 单位
     *
     * @type {string}
     * @memberof PrintTestItemDto
     */
    unit?: string | null;

    /**
     * 临床意义
     *
     * @type {string}
     * @memberof PrintTestItemDto
     */
    remark?: string | null;

    /**
     * 最大值
     *
     * @type {string}
     * @memberof PrintTestItemDto
     */
    maxValue?: string | null;

    /**
     * 最小值
     *
     * @type {string}
     * @memberof PrintTestItemDto
     */
    minValue?: string | null;

    /**
     * 结果值
     *
     * @type {string}
     * @memberof PrintTestItemDto
     */
    resultValue?: string | null;
}
