/* tslint:disable */
/* eslint-disable */
/**
 * 文书模板管理
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SysDocumentTemplatesPageInput
 */
export interface SysDocumentTemplatesPageInput {

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof SysDocumentTemplatesPageInput
     */
    createTime?: Date | null;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof SysDocumentTemplatesPageInput
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof SysDocumentTemplatesPageInput
     */
    createUserId?: number | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof SysDocumentTemplatesPageInput
     */
    updateUserId?: number | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof SysDocumentTemplatesPageInput
     */
    isDelete?: boolean;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof SysDocumentTemplatesPageInput
     */
    ver?: string | null;

    /**
     * 创建者部门名称
     *
     * @type {string}
     * @memberof SysDocumentTemplatesPageInput
     */
    createOrgName?: string | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof SysDocumentTemplatesPageInput
     */
    updateUserName?: string | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof SysDocumentTemplatesPageInput
     */
    createUserName?: string | null;

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof SysDocumentTemplatesPageInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof SysDocumentTemplatesPageInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof SysDocumentTemplatesPageInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof SysDocumentTemplatesPageInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof SysDocumentTemplatesPageInput
     */
    descStr?: string | null;

    /**
     * 名称
     *
     * @type {string}
     * @memberof SysDocumentTemplatesPageInput
     */
    name?: string | null;
}
