/* tslint:disable */
/* eslint-disable */
/**
 * 库存管理
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OutStorageDeatilsDto
 */
export interface OutStorageDeatilsDto {
    /**
     * 创建时间
     * @type {Date}
     * @memberof OutStorageDeatilsDto
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof OutStorageDeatilsDto
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof OutStorageDeatilsDto
     */
    createUserId?: number | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof OutStorageDeatilsDto
     */
    updateUserId?: number | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof OutStorageDeatilsDto
     */
    isDelete?: boolean;
    /**
     * 版本标识
     * @type {string}
     * @memberof OutStorageDeatilsDto
     */
    ver?: string | null;
    /**
     * 产品名称
     * @type {string}
     * @memberof OutStorageDeatilsDto
     */
    productName: string;
    /**
     * 产品id
     * @type {string}
     * @memberof OutStorageDeatilsDto
     */
    productId: string;
    /**
     * 产品类型
     * @type {string}
     * @memberof OutStorageDeatilsDto
     */
    productType?: string | null;
    /**
     * 产品编码
     * @type {string}
     * @memberof OutStorageDeatilsDto
     */
    productCode?: string | null;
    /**
     * 目录ID
     * @type {number}
     * @memberof OutStorageDeatilsDto
     */
    categoryId?: number;
    /**
     * 目录名称
     * @type {string}
     * @memberof OutStorageDeatilsDto
     */
    categoryName?: string | null;
    /**
     * 单位id
     * @type {number}
     * @memberof OutStorageDeatilsDto
     */
    unitId?: number | null;
    /**
     * 单位名称
     * @type {string}
     * @memberof OutStorageDeatilsDto
     */
    unitName?: string | null;
    /**
     * 采购数
     * @type {number}
     * @memberof OutStorageDeatilsDto
     */
    procureCount?: number;
    /**
     * 赠送数
     * @type {number}
     * @memberof OutStorageDeatilsDto
     */
    giveCount?: number | null;
    /**
     * 总金额
     * @type {number}
     * @memberof OutStorageDeatilsDto
     */
    amount?: number;
    /**
     * 出库单价
     * @type {number}
     * @memberof OutStorageDeatilsDto
     */
    singPrice?: number;
    /**
     * 采购单价
     * @type {number}
     * @memberof OutStorageDeatilsDto
     */
    inPrice?: number;
    /**
     * 备注
     * @type {string}
     * @memberof OutStorageDeatilsDto
     */
    remark?: string | null;
}
