/* tslint:disable */
/* eslint-disable */
/**
 * 订单支付
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PaymentDetailInput } from './payment-detail-input';
import { PaymentMethodInput } from './payment-method-input';
 /**
 * 支付请求参数
 *
 * @export
 * @interface PaymentInput
 */
export interface PaymentInput {

    /**
     * 实付金额
     *
     * @type {number}
     * @memberof PaymentInput
     */
    actlyAmount?: number;

    /**
     * 抹零金额
     *
     * @type {number}
     * @memberof PaymentInput
     */
    downIntegerAmount?: number;

    /**
     * 订单备注
     *
     * @type {string}
     * @memberof PaymentInput
     */
    remark?: string | null;

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof PaymentInput
     */
    customerId?: number;

    /**
     * 用户名称
     *
     * @type {string}
     * @memberof PaymentInput
     */
    customerName?: string | null;

    /**
     * 支付明细
     *
     * @type {Array<PaymentDetailInput>}
     * @memberof PaymentInput
     */
    paymentDetails?: Array<PaymentDetailInput> | null;

    /**
     * 支付方式
     *
     * @type {Array<PaymentMethodInput>}
     * @memberof PaymentInput
     */
    paymentMethods?: Array<PaymentMethodInput> | null;
}
