/* tslint:disable */
/* eslint-disable */
/**
 * 订单支付
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PaymentMethodInput
 */
export interface PaymentMethodInput {

    /**
     * 支付类型ID
     *
     * @type {number}
     * @memberof PaymentMethodInput
     */
    id?: number;

    /**
     * 支付类型名称
     *
     * @type {string}
     * @memberof PaymentMethodInput
     */
    name?: string | null;

    /**
     * 标识
     *
     * @type {string}
     * @memberof PaymentMethodInput
     */
    code?: string | null;

    /**
     * 支付金额  ( 如果是次卡值就是次卡抵扣的金额 )
     *
     * @type {number}
     * @memberof PaymentMethodInput
     */
    amount?: number;
    /**
     * 使用次数
     *
     * @type {number}
     * @memberof PaymentMethodInput
     */
    totalCount?: number;

    /**
     * 业务Id
     *
     * @type {number}
     * @memberof PaymentMethodInput
     */
    businessId?: number;

    /**
     * 业务表对应的版本标识
     *
     * @type {string}
     * @memberof PaymentMethodInput
     */
    businessVer?: string | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof PaymentMethodInput
     */
    remark?: string | null;
}
