/* tslint:disable */
/* eslint-disable */
/**
 * 系统退单
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PaymentMethodInput } from './payment-method-input';
import { ReturnPaymentDetailsInput } from './return-payment-details-input';
 /**
 * 退单输入参数
 *
 * @export
 * @interface ReturnPaymentsInput
 */
export interface ReturnPaymentsInput {

    /**
     * 支付Id
     *
     * @type {number}
     * @memberof ReturnPaymentsInput
     */
    paymentId?: number;

    /**
     * 订单编号
     *
     * @type {string}
     * @memberof ReturnPaymentsInput
     */
    serialNumber?: string | null;

    /**
     * 订单表版本标识
     *
     * @type {string}
     * @memberof ReturnPaymentsInput
     */
    paymentVer?: string | null;

    /**
     * 退单备注
     *
     * @type {string}
     * @memberof ReturnPaymentsInput
     */
    remark?: string | null;

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof ReturnPaymentsInput
     */
    customerId?: number;

    /**
     * 支付方式
     *
     * @type {Array<PaymentMethodInput>}
     * @memberof ReturnPaymentsInput
     */
    paymentMethods?: Array<PaymentMethodInput> | null;

    /**
     * 退款明细
     *
     * @type {Array<ReturnPaymentDetailsInput>}
     * @memberof ReturnPaymentsInput
     */
    returnPaymentDetails?: Array<ReturnPaymentDetailsInput> | null;
}
