/* tslint:disable */
/* eslint-disable */
/**
 * 待付款相关
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WillPaymentPetOutput
 */
export interface WillPaymentPetOutput {
    /**
     * 宠物ID
     * @type {number}
     * @memberof WillPaymentPetOutput
     */
    id?: number;
    /**
     * 宠主id
     * @type {number}
     * @memberof WillPaymentPetOutput
     */
    customerId?: number | null;
    /**
     * 宠物名称
     * @type {string}
     * @memberof WillPaymentPetOutput
     */
    petName?: string | null;
}
