/* tslint:disable */
/* eslint-disable */
/**
 * 打印和预览相关服务
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MicroReportInput
 */
export interface MicroReportInput {

    /**
     * 病例Id
     *
     * @type {number}
     * @memberof MicroReportInput
     */
    recordId?: number;

    /**
     * 病例Id
     *
     * @type {number}
     * @memberof MicroReportInput
     */
    regId?: number;

    /**
     * 化验项目Id
     *
     * @type {number}
     * @memberof MicroReportInput
     */
    testItemId?: number;
}
