/* tslint:disable */
/* eslint-disable */
/**
 * 病例相关打印
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CEMDocPayTypeEnum } from './cemdoc-pay-type-enum';
import { ProductTypeEnums } from './product-type-enums';
 /**
 * 化验明细输出参数
 *
 * @export
 * @interface TestItemOutput
 */
export interface TestItemOutput {

    /**
     * 化验主表id
     *
     * @type {number}
     * @memberof TestItemOutput
     */
    recordTestId?: number;

    /**
     * 产品id
     *
     * @type {number}
     * @memberof TestItemOutput
     */
    itemId?: number;

    /**
     * 产品名称
     *
     * @type {string}
     * @memberof TestItemOutput
     */
    itemName?: string | null;

    /**
     * @type {ProductTypeEnums}
     * @memberof TestItemOutput
     */
    type?: ProductTypeEnums;

    /**
     * 单位id
     *
     * @type {number}
     * @memberof TestItemOutput
     */
    unitId?: number | null;

    /**
     * 单位名称
     *
     * @type {string}
     * @memberof TestItemOutput
     */
    unitName?: string | null;

    /**
     * 处方医生Id
     *
     * @type {number}
     * @memberof TestItemOutput
     */
    doctorId?: number;

    /**
     * 处方医生
     *
     * @type {string}
     * @memberof TestItemOutput
     */
    doctorName?: string | null;

    /**
     * 数量
     *
     * @type {number}
     * @memberof TestItemOutput
     */
    count?: number;

    /**
     * 单价
     *
     * @type {number}
     * @memberof TestItemOutput
     */
    salePrice?: number;

    /**
     * 总金额
     *
     * @type {number}
     * @memberof TestItemOutput
     */
    amountPrice?: number;

    /**
     * 检查医生id
     *
     * @type {number}
     * @memberof TestItemOutput
     */
    inspectDoctorId?: number | null;

    /**
     * 检查医生名称
     *
     * @type {string}
     * @memberof TestItemOutput
     */
    inspectDoctorName?: string | null;

    /**
     * 助理id
     *
     * @type {number}
     * @memberof TestItemOutput
     */
    assistantId?: number | null;

    /**
     * 助理名称
     *
     * @type {string}
     * @memberof TestItemOutput
     */
    assistantName?: string | null;

    /**
     * 开单时间
     *
     * @type {Date}
     * @memberof TestItemOutput
     */
    billingTime?: Date;

    /**
     * 检查时间
     *
     * @type {Date}
     * @memberof TestItemOutput
     */
    inspectTime?: Date | null;

    /**
     * 支付时间
     *
     * @type {Date}
     * @memberof TestItemOutput
     */
    payTime?: Date | null;

    /**
     * 支付效验码
     *
     * @type {string}
     * @memberof TestItemOutput
     */
    payValidation?: string | null;

    /**
     * @type {CEMDocPayTypeEnum}
     * @memberof TestItemOutput
     */
    payStatus?: CEMDocPayTypeEnum;

    /**
     * 是否手动改价
     *
     * @type {boolean}
     * @memberof TestItemOutput
     */
    isEditPrice?: boolean;

    /**
     * 备注
     *
     * @type {string}
     * @memberof TestItemOutput
     */
    remark?: string | null;

    /**
     * 是否套餐项目
     *
     * @type {boolean}
     * @memberof TestItemOutput
     */
    isMeal?: boolean;

    /**
     * 报告状态
     *
     * @type {boolean}
     * @memberof TestItemOutput
     */
    isReport?: boolean;
}
