/* tslint:disable */
/* eslint-disable */
/**
 * 病例管理
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CEMDocPayTypeEnum } from './cemdoc-pay-type-enum';
import { ProductTypeEnums } from './product-type-enums';
 /**
 * 处方打包/套餐表
 *
 * @export
 * @interface CEMRecordPrescriptionItemPack
 */
export interface CEMRecordPrescriptionItemPack {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof CEMRecordPrescriptionItemPack
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof CEMRecordPrescriptionItemPack
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof CEMRecordPrescriptionItemPack
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof CEMRecordPrescriptionItemPack
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof CEMRecordPrescriptionItemPack
     */
    isDelete?: boolean;

    /**
     * @type {string}
     * @memberof CEMRecordPrescriptionItemPack
     */
    ver?: string | null;

    /**
     * 创建者部门Id
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    createOrgId?: number | null;

    /**
     * 创建者部门名称
     *
     * @type {string}
     * @memberof CEMRecordPrescriptionItemPack
     */
    createOrgName?: string | null;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    tenantId?: number | null;

    /**
     * 病例id
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    recordId?: number;

    /**
     * 挂号id
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    regId?: number;

    /**
     * 处方明细表id
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    prescriptionItemId?: number;

    /**
     * 项目id
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    itemId?: number;

    /**
     * 项目名称
     *
     * @type {string}
     * @memberof CEMRecordPrescriptionItemPack
     */
    itemName?: string | null;

    /**
     * @type {ProductTypeEnums}
     * @memberof CEMRecordPrescriptionItemPack
     */
    type?: ProductTypeEnums;

    /**
     * 单位id
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    unitId?: number | null;

    /**
     * 单位名称
     *
     * @type {string}
     * @memberof CEMRecordPrescriptionItemPack
     */
    unitName?: string | null;

    /**
     * 规格
     *
     * @type {string}
     * @memberof CEMRecordPrescriptionItemPack
     */
    specific?: string | null;

    /**
     * 单次用量
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    useDose?: number | null;

    /**
     * 次/天
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    useMethods?: number | null;

    /**
     * 天数
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    dayNum?: number | null;

    /**
     * 总次数
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    amountCount?: number | null;

    /**
     * 处方医生Id
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    doctorId?: number;

    /**
     * 处方医生
     *
     * @type {string}
     * @memberof CEMRecordPrescriptionItemPack
     */
    doctorName?: string | null;

    /**
     * 数量
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    count?: number;

    /**
     * 单价
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    salePrice?: number;

    /**
     * 总金额
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    amountPrice?: number;

    /**
     * 是否打包
     *
     * @type {boolean}
     * @memberof CEMRecordPrescriptionItemPack
     */
    isPack?: boolean;

    /**
     * 使用方式
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    dosingWay?: number;

    /**
     * 分组
     *
     * @type {number}
     * @memberof CEMRecordPrescriptionItemPack
     */
    orderId?: number | null;

    /**
     * 分组
     *
     * @type {string}
     * @memberof CEMRecordPrescriptionItemPack
     */
    orderName?: string | null;

    /**
     * 支付时间
     *
     * @type {Date}
     * @memberof CEMRecordPrescriptionItemPack
     */
    payTime?: Date | null;

    /**
     * @type {CEMDocPayTypeEnum}
     * @memberof CEMRecordPrescriptionItemPack
     */
    payStatus?: CEMDocPayTypeEnum;
}
