/* tslint:disable */
/* eslint-disable */
/**
 * 病例管理
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CEMRecordTestItemDto } from './cemrecord-test-item-dto';
 /**
 * 
 *
 * @export
 * @interface CEMRecordTestDto
 */
export interface CEMRecordTestDto {

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof CEMRecordTestDto
     */
    createTime?: Date | null;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof CEMRecordTestDto
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof CEMRecordTestDto
     */
    createUserId?: number | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof CEMRecordTestDto
     */
    updateUserId?: number | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof CEMRecordTestDto
     */
    isDelete?: boolean;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof CEMRecordTestDto
     */
    ver?: string | null;

    /**
     * 创建者部门名称
     *
     * @type {string}
     * @memberof CEMRecordTestDto
     */
    createOrgName?: string | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof CEMRecordTestDto
     */
    updateUserName?: string | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof CEMRecordTestDto
     */
    createUserName?: string | null;

    /**
     * @type {number}
     * @memberof CEMRecordTestDto
     */
    id?: number;

    /**
     * 病例id
     *
     * @type {number}
     * @memberof CEMRecordTestDto
     */
    recordId?: number;

    /**
     * 挂号id
     *
     * @type {number}
     * @memberof CEMRecordTestDto
     */
    regId?: number;

    /**
     * 是否住院
     *
     * @type {boolean}
     * @memberof CEMRecordPrescriptionItem
     */
    isHospital?: boolean;
    /**
     * 开单时间
     *
     * @type {Date}
     * @memberof CEMRecordTestDto
     */
    billingTime?: Date;

    /**
     * 总金额
     *
     * @type {number}
     * @memberof CEMRecordTestDto
     */
    amountPrice?: number;

    /**
     * 项目数量
     *
     * @type {number}
     * @memberof CEMRecordTestDto
     */
    count?: number;

    /**
     * 套餐id
     *
     * @type {number}
     * @memberof CEMRecordTestDto
     */
    packageId?: number | null;

    /**
     * 套餐名称
     *
     * @type {string}
     * @memberof CEMRecordTestDto
     */
    packageName?: string | null;

    /**
     * 套餐金额
     *
     * @type {number}
     * @memberof CEMRecordTestDto
     */
    packagePrice?: number;

    /**
     * 化验项目信息
     *
     * @type {Array<CEMRecordTestItemDto>}
     * @memberof CEMRecordTestDto
     */
    cemRecordTestItem?: Array<CEMRecordTestItemDto> | null;
}
