/* tslint:disable */
/* eslint-disable */
/**
 * 病例管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RegType } from './reg-type';
import { RegistersStatusEnum } from './registers-status-enum';
 /**
 * 
 *
 * @export
 * @interface CEMRecordPetOutput
 */
export interface CEMRecordPetOutput {

    /**
     * 挂号Id
     *
     * @type {number}
     * @memberof CEMRecordPetOutput
     */
    id?: number;

    /**
     * 病例Id
     *
     * @type {number}
     * @memberof CEMRecordPetOutput
     */
    recordId?: number;

    /**
     * 挂号时间  挂号表的创建时间
     *
     * @type {Date}
     * @memberof CEMRecordPetOutput
     */
    regTime?: Date | null;

    /**
     * 就诊时间  病例表的创建时间
     *
     * @type {Date}
     * @memberof CEMRecordPetOutput
     */
    recordTime?: Date | null;

    /**
     * 病例结束时间  病例表的更新时间
     *
     * @type {Date}
     * @memberof CEMRecordPetOutput
     */
    updateTime?: Date | null;

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof CEMRecordPetOutput
     */
    customerId?: number;

    /**
     * 用户名称
     *
     * @type {string}
     * @memberof CEMRecordPetOutput
     */
    customerName?: string | null;

    /**
     * 宠物Id
     *
     * @type {number}
     * @memberof CEMRecordPetOutput
     */
    petId?: number;

    /**
     * 宠物名称
     *
     * @type {string}
     * @memberof CEMRecordPetOutput
     */
    petName?: string | null;

    /**
     * @type {RegistersStatusEnum}
     * @memberof CEMRecordPetOutput
     */
    status?: RegistersStatusEnum;

    /**
     * @type {RegType}
     * @memberof CEMRecordPetOutput
     */
    regType?: RegType;

    /**
     * 挂号类型
     *
     * @type {string}
     * @memberof CEMRecordPetOutput
     */
    regTypeText?: string | null;

    /**
     * 挂号状态
     *
     * @type {string}
     * @memberof CEMRecordPetOutput
     */
    statusText?: string | null;

    /**
     * 是否住院病历
     *
     * @type {boolean}
     * @memberof CEMRecordPetOutput
     */
    isHospital?: boolean | null;

    /**
     * 就诊医生id
     *
     * @type {number}
     * @memberof CEMRecordPetOutput
     */
    visitDoctorId?: number | null;

    /**
     * 就诊医生名称
     *
     * @type {string}
     * @memberof CEMRecordPetOutput
     */
    visitDoctorName?: string | null;
}
