/* tslint:disable */
/* eslint-disable */
/**
 * 病例管理
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CEMRecordPhysicalDetails } from './cemrecord-physical-details';
import {
    CEMRecordPhysicalDetails,
} from ".";

/**
 * 
 *
 * @export
 * @interface CEMRecordPhysicalDto
 */
export interface CEMRecordPhysicalDto {

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof CEMRecordPhysicalDto
     */
    createTime?: Date | null;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof CEMRecordPhysicalDto
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof CEMRecordPhysicalDto
     */
    createUserId?: number | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof CEMRecordPhysicalDto
     */
    updateUserId?: number | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof CEMRecordPhysicalDto
     */
    isDelete?: boolean;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof CEMRecordPhysicalDto
     */
    ver?: string | null;

    /**
     * 创建者部门名称
     *
     * @type {string}
     * @memberof CEMRecordPhysicalDto
     */
    createOrgName?: string | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof CEMRecordPhysicalDto
     */
    updateUserName?: string | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof CEMRecordPhysicalDto
     */
    createUserName?: string | null;

    /**
     * 病例id
     *
     * @type {number}
     * @memberof CEMRecordPhysicalDto
     */
    recordId?: number;

    /**
     * 挂号id
     *
     * @type {number}
     * @memberof CEMRecordPhysicalDto
     */
    regId?: number;

    /**
     * 体重
     *
     * @type {number}
     * @memberof CEMRecordPhysicalDto
     */
    petWeight?: number | null;

    /**
     * 体温
     *
     * @type {number}
     * @memberof CEMRecordPhysicalDto
     */
    temperature?: number | null;

    /**
     * 呼吸频率
     *
     * @type {number}
     * @memberof CEMRecordPhysicalDto
     */
    respiratoryRate?: number | null;

    /**
     * CRT(S)
     *
     * @type {number}
     * @memberof CEMRecordPhysicalDto
     */
    crt?: number | null;

    /**
     * BCS评分
     *
     * @type {number}
     * @memberof CEMRecordPhysicalDto
     */
    bcs?: number | null;

    /**
     * 检查项目明细
     *
     * @type {Array<CEMRecordPhysicalDetails>}
     * @memberof CEMRecordPhysicalDto
     */
    cemRecordPhysicalDetails?: Array<CEMRecordPhysicalDetails> | null;
}
