/* tslint:disable */
/* eslint-disable */
/**
 * 病例管理
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CEMRecordPhysicalExamItemOptions } from './cemrecord-physical-exam-item-options';
import { CEMRecordPhysicalExamItemResult } from './cemrecord-physical-exam-item-result';
 /**
 * 诊疗体格检查项目
 *
 * @export
 * @interface CEMRecordPhysicalExamItemDto
 */
export interface CEMRecordPhysicalExamItemDto {

    /**
     * 体格检查项目Id,PhysicalExamItem.Id
     *
     * @type {number}
     * @memberof CEMRecordPhysicalExamItemDto
     */
    physicalExamItemId?: number;

    /**
     * 体格检查类型Id，PhysicalExamType.Id
     *
     * @type {number}
     * @memberof CEMRecordPhysicalExamItemDto
     */
    physicalExamTypeId?: number;

    /**
     * 体格检查项目名称
     *
     * @type {string}
     * @memberof CEMRecordPhysicalExamItemDto
     */
    name?: string | null;

    /**
     * 体格检查项目项目值类型：0=是否、1=单项、2=输入文本、3=多选
     *
     * @type {number}
     * @memberof CEMRecordPhysicalExamItemDto
     */
    valueType?: number;

    /**
     * 排序
     *
     * @type {number}
     * @memberof CEMRecordPhysicalExamItemDto
     */
    seq?: number;

    /**
     * 行号
     *
     * @type {number}
     * @memberof CEMRecordPhysicalExamItemDto
     */
    rowNum?: number;

    /**
     * 诊疗体格检查项目选项列表
     *
     * @type {Array<CEMRecordPhysicalExamItemOptions>}
     * @memberof CEMRecordPhysicalExamItemDto
     */
    options?: Array<CEMRecordPhysicalExamItemOptions> | null;

    /**
     * @type {CEMRecordPhysicalExamItemResult}
     * @memberof CEMRecordPhysicalExamItemDto
     */
    result?: CEMRecordPhysicalExamItemResult;
}
