/* tslint:disable */
/* eslint-disable */
/**
 * 病例管理
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RegType } from './reg-type';
import { RegistersStatusEnum } from './registers-status-enum';
 /**
 * 病例主表model
 *
 * @export
 * @interface CEMRecordDto
 */
export interface CEMRecordDto {

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof CEMRecordDto
     */
    createTime?: Date | null;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof CEMRecordDto
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof CEMRecordDto
     */
    createUserId?: number | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof CEMRecordDto
     */
    updateUserId?: number | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof CEMRecordDto
     */
    isDelete?: boolean;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof CEMRecordDto
     */
    ver?: string | null;

    /**
     * 创建者部门名称
     *
     * @type {string}
     * @memberof CEMRecordDto
     */
    createOrgName?: string | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof CEMRecordDto
     */
    updateUserName?: string | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof CEMRecordDto
     */
    createUserName?: string | null;

    /**
     * Id
     *
     * @type {number}
     * @memberof CEMRecordDto
     */
    id?: number;

    /**
     * 挂号id
     *
     * @type {number}
     * @memberof CEMRecordDto
     */
    regId?: number;

    /**
     * @type {RegType}
     * @memberof CEMRecordDto
     */
    regType?: RegType;

    /**
     * 就诊医生id
     *
     * @type {number}
     * @memberof CEMRecordDto
     */
    visitDoctorId?: number;

    /**
     * 就诊医生名称
     *
     * @type {string}
     * @memberof CEMRecordDto
     */
    visitDoctorName?: string | null;

    /**
     * 用户id
     *
     * @type {number}
     * @memberof CEMRecordDto
     */
    customerId?: number;

    /**
     * 用户名称
     *
     * @type {string}
     * @memberof CEMRecordDto
     */
    customerName?: string | null;

    /**
     * 用户手机号
     *
     * @type {string}
     * @memberof CEMRecordDto
     */
    customerPhone?: string | null;

    /**
     * 宠物id
     *
     * @type {number}
     * @memberof CEMRecordDto
     */
    petId?: number;

    /**
     * 宠物名称
     *
     * @type {string}
     * @memberof CEMRecordDto
     */
    petName?: string | null;

    /**
     * 病例编号
     *
     * @type {string}
     * @memberof CEMRecordDto
     */
    orderNo?: string | null;

    /**
     * @type {RegistersStatusEnum}
     * @memberof CEMRecordDto
     */
    status?: RegistersStatusEnum;
}
