/* tslint:disable */
/* eslint-disable */
/**
 * 病例管理
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CEMRecordPhysicalExamItemResult } from './cemrecord-physical-exam-item-result';
import { CEMRecordPhysicalExamTypeDto } from './cemrecord-physical-exam-type-dto';
 /**
 * 诊疗体格检查详情
 *
 * @export
 * @interface CEMRecordPhysicalExamDetailDto
 */
export interface CEMRecordPhysicalExamDetailDto {

    /**
     * 预约Id
     *
     * @type {number}
     * @memberof CEMRecordPhysicalExamDetailDto
     */
    regId: number;

    /**
     * 病例id
     *
     * @type {number}
     * @memberof CEMRecordPhysicalExamDetailDto
     */
    recordId: number;

    /**
     * 体重
     *
     * @type {number}
     * @memberof CEMRecordPhysicalExamDetailDto
     */
    petWeight?: number | null;

    /**
     * 体温
     *
     * @type {number}
     * @memberof CEMRecordPhysicalExamDetailDto
     */
    temperature?: number | null;

    /**
     * 呼吸频率
     *
     * @type {number}
     * @memberof CEMRecordPhysicalExamDetailDto
     */
    respiratoryRate?: number | null;

    /**
     * 心率
     *
     * @type {number}
     * @memberof CEMRecordPhysicalExamDetailDto
     */
    heartRate?: number | null;

    /**
     * CRT(S)
     *
     * @type {number}
     * @memberof CEMRecordPhysicalExamDetailDto
     */
    crt?: number | null;

    /**
     * BCS评分
     *
     * @type {number}
     * @memberof CEMRecordPhysicalExamDetailDto
     */
    bcs?: number | null;

    /**
     * 诊疗体格检查类型列表
     *
     * @type {Array<CEMRecordPhysicalExamTypeDto>}
     * @memberof CEMRecordPhysicalExamDetailDto
     */
    types: Array<CEMRecordPhysicalExamTypeDto>;

    /**
     * 体格检查项目结果
     *
     * @type {Array<CEMRecordPhysicalExamItemResult>}
     * @memberof CEMRecordPhysicalExamDetailDto
     */
    results?: Array<CEMRecordPhysicalExamItemResult> | null;
}
