/* tslint:disable */
/* eslint-disable */
/**
 * 住院留观
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InHospitalDetailInput
 */
export interface InHospitalDetailInput {

    /**
     * 住院Id
     *
     * @type {number}
     * @memberof InHospitalDetailInput
     */
    id?: number;

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof InHospitalDetailInput
     */
    customerId?: number;

    /**
     * 病例Id
     *
     * @type {number}
     * @memberof InHospitalDetailInput
     */
    recordId?: number;

    /**
     * 挂号Id
     *
     * @type {number}
     * @memberof InHospitalDetailInput
     */
    regId?: number;
}
