/* tslint:disable */
/* eslint-disable */
/**
 * 住院寄养
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InHospitalTypeEnum } from './in-hospital-type-enum';
 /**
 * 
 *
 * @export
 * @interface InHospitalNursePageInput
 */
export interface InHospitalNursePageInput {

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof InHospitalNursePageInput
     */
    createTime?: Date | null;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof InHospitalNursePageInput
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof InHospitalNursePageInput
     */
    createUserId?: number | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof InHospitalNursePageInput
     */
    updateUserId?: number | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof InHospitalNursePageInput
     */
    isDelete?: boolean;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof InHospitalNursePageInput
     */
    ver?: string | null;

    /**
     * 创建者部门名称
     *
     * @type {string}
     * @memberof InHospitalNursePageInput
     */
    createOrgName?: string | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof InHospitalNursePageInput
     */
    updateUserName?: string | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof InHospitalNursePageInput
     */
    createUserName?: string | null;

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof InHospitalNursePageInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof InHospitalNursePageInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof InHospitalNursePageInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof InHospitalNursePageInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof InHospitalNursePageInput
     */
    descStr?: string | null;

    /**
     * 项目名称
     *
     * @type {string}
     * @memberof InHospitalNursePageInput
     */
    name?: string | null;

    /**
     * @type {InHospitalTypeEnum}
     * @memberof InHospitalNursePageInput
     */
    inHospitalType?: InHospitalTypeEnum;
}
