/* tslint:disable */
/* eslint-disable */
/**
 * 住院留观
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 出院请求参数
 *
 * @export
 * @interface OutHospitalInput
 */
export interface OutHospitalInput {

    /**
     * 住院Id
     *
     * @type {number}
     * @memberof OutHospitalInput
     */
    id?: number;

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof OutHospitalInput
     */
    customerId?: number;

    /**
     * 宠物Id
     *
     * @type {number}
     * @memberof OutHospitalInput
     */
    petId?: number;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof OutHospitalInput
     */
    ver?: string | null;
}
