/* tslint:disable */
/* eslint-disable */
/**
 * 病例管理
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 诊疗步骤<br />&nbsp;主诉 ZhuSu = 0<br />&nbsp;体格检查 Pyhysical = 1<br />&nbsp;检查化验 Test = 2<br />&nbsp;疾病诊断 Diagnosis = 3<br />&nbsp;处方 Prescription = 4<br />&nbsp;医嘱 Advice = 5<br />&nbsp;回访 Follow = 6<br />
 * @export
 * @enum {string}
 */
export enum RecordStepEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6
}

