/* tslint:disable */
/* eslint-disable */
/**
 * 住院留观
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InHospitalNurseOutput } from './in-hospital-nurse-output';
 /**
 * 分页泛型集合
 *
 * @export
 * @interface SqlSugarPagedListInHospitalNurseOutput
 */
export interface SqlSugarPagedListInHospitalNurseOutput {

    /**
     * 页码
     *
     * @type {number}
     * @memberof SqlSugarPagedListInHospitalNurseOutput
     */
    page?: number;

    /**
     * 页容量
     *
     * @type {number}
     * @memberof SqlSugarPagedListInHospitalNurseOutput
     */
    pageSize?: number;

    /**
     * 总条数
     *
     * @type {number}
     * @memberof SqlSugarPagedListInHospitalNurseOutput
     */
    total?: number;

    /**
     * 总页数
     *
     * @type {number}
     * @memberof SqlSugarPagedListInHospitalNurseOutput
     */
    totalPages?: number;

    /**
     * 当前页集合
     *
     * @type {Array<InHospitalNurseOutput>}
     * @memberof SqlSugarPagedListInHospitalNurseOutput
     */
    items?: Array<InHospitalNurseOutput> | null;

    /**
     * 是否有上一页
     *
     * @type {boolean}
     * @memberof SqlSugarPagedListInHospitalNurseOutput
     */
    hasPrevPage?: boolean;

    /**
     * 是否有下一页
     *
     * @type {boolean}
     * @memberof SqlSugarPagedListInHospitalNurseOutput
     */
    hasNextPage?: boolean;
}
