/* tslint:disable */
/* eslint-disable */
/**
 * 住院留观
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InHospitalRecordOutput } from './in-hospital-record-output';
 /**
 * 分页泛型集合
 *
 * @export
 * @interface SqlSugarPagedListInHospitalRecordOutput
 */
export interface SqlSugarPagedListInHospitalRecordOutput {

    /**
     * 页码
     *
     * @type {number}
     * @memberof SqlSugarPagedListInHospitalRecordOutput
     */
    page?: number;

    /**
     * 页容量
     *
     * @type {number}
     * @memberof SqlSugarPagedListInHospitalRecordOutput
     */
    pageSize?: number;

    /**
     * 总条数
     *
     * @type {number}
     * @memberof SqlSugarPagedListInHospitalRecordOutput
     */
    total?: number;

    /**
     * 总页数
     *
     * @type {number}
     * @memberof SqlSugarPagedListInHospitalRecordOutput
     */
    totalPages?: number;

    /**
     * 当前页集合
     *
     * @type {Array<InHospitalRecordOutput>}
     * @memberof SqlSugarPagedListInHospitalRecordOutput
     */
    items?: Array<InHospitalRecordOutput> | null;

    /**
     * 是否有上一页
     *
     * @type {boolean}
     * @memberof SqlSugarPagedListInHospitalRecordOutput
     */
    hasPrevPage?: boolean;

    /**
     * 是否有下一页
     *
     * @type {boolean}
     * @memberof SqlSugarPagedListInHospitalRecordOutput
     */
    hasNextPage?: boolean;
}
