/* tslint:disable */
/* eslint-disable */
/**
 * 住院留观
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateInHospitalRoomsInput
 */
export interface UpdateInHospitalRoomsInput {

    /**
     * 住院Id
     *
     * @type {number}
     * @memberof UpdateInHospitalRoomsInput
     */
    id?: number;

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof UpdateInHospitalRoomsInput
     */
    customerId?: number;

    /**
     * 住院标识
     *
     * @type {string}
     * @memberof UpdateInHospitalRoomsInput
     */
    ver?: string | null;

    /**
     * 源笼位Id
     *
     * @type {number}
     * @memberof UpdateInHospitalRoomsInput
     */
    sourceId?: number;

    /**
     * 源笼位标识
     *
     * @type {string}
     * @memberof UpdateInHospitalRoomsInput
     */
    sourceVer?: string | null;

    /**
     * 现笼位Id
     *
     * @type {number}
     * @memberof UpdateInHospitalRoomsInput
     */
    nowId?: number;

    /**
     * 现笼位标识
     *
     * @type {string}
     * @memberof UpdateInHospitalRoomsInput
     */
    nowVer?: string | null;
}
