/* tslint:disable */
/* eslint-disable */
/**
 * 驱虫疫苗
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { VaccinationInfo } from './vaccination-info';
import {
    VaccinationInfo,
} from ".";

/**
 * 
 *
 * @export
 * @interface VaccinationInput
 */
export interface VaccinationInput {

    /**
     * 是否发送短信
     *
     * @type {boolean}
     * @memberof VaccinationInput
     */
    isSendSMS?: boolean;

    /**
     * 手机号码
     *
     * @type {string}
     * @memberof VaccinationInput
     */
    cellPhone?: string | null;

    /**
     * 操作人Id
     *
     * @type {number}
     * @memberof VaccinationInput
     */
    operateId?: number;

    /**
     * 操作人名称
     *
     * @type {string}
     * @memberof VaccinationInput
     */
    operateName?: string | null;

    /**
     * 短信模板Id
     *
     * @type {number}
     * @memberof VaccinationInput
     */
    templateId?: number;

    /**
     * 疫苗信息
     *
     * @type {Array<VaccinationInfo>}
     * @memberof VaccinationInput
     */
    vaccinationInfos?: Array<VaccinationInfo> | null;
}
