/* tslint:disable */
/* eslint-disable */
/**
 * 驱虫疫苗
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 疫苗开具请求参数
 *
 * @export
 * @interface VaccinationIssueInput
 */
export interface VaccinationIssueInput {

    /**
     * 产品名称
     *
     * @type {string}
     * @memberof VaccinationIssueInput
     */
    name?: string | null;
}
