/* tslint:disable */
/* eslint-disable */
/**
 * 驱虫疫苗
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Vaccinations } from './vaccinations';
import {
    Vaccinations,
} from ".";

/**
 * 
 *
 * @export
 * @interface VaccinationDetailsOutput
 */
export interface VaccinationDetailsOutput {

    /**
     * 操作人Id
     *
     * @type {number}
     * @memberof VaccinationDetailsOutput
     */
    operateId?: number;

    /**
     * 操作人名称
     *
     * @type {string}
     * @memberof VaccinationDetailsOutput
     */
    operateName?: string | null;

    /**
     * 短信模板Id
     *
     * @type {number}
     * @memberof VaccinationDetailsOutput
     */
    templateId?: number;

    /**
     * 短信内容
     *
     * @type {string}
     * @memberof VaccinationDetailsOutput
     */
    content?: string | null;

    /**
     * @type {Vaccinations}
     * @memberof VaccinationDetailsOutput
     */
    vaccinations?: Vaccinations;
}
