/* tslint:disable */
/* eslint-disable */
/**
 * 病例管理
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 主诉输出参数
 *
 * @export
 * @interface ZhuSuOutput
 */
export interface ZhuSuOutput {

    /**
     * 主诉
     *
     * @type {string}
     * @memberof ZhuSuOutput
     */
    zhuSu?: string | null;

    /**
     * 既往史
     *
     * @type {string}
     * @memberof ZhuSuOutput
     */
    pastHistory?: string | null;

    /**
     * 过敏史
     *
     * @type {string}
     * @memberof ZhuSuOutput
     */
    allergyHistory?: string | null;
}
