/* tslint:disable */
/* eslint-disable */
/**
 * 叫号服务
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CallNumberInput
 */
export interface CallNumberInput {

    /**
     * 诊室Id
     *
     * @type {number}
     * @memberof CallNumberInput
     */
    id?: number;

    /**
     * 排队编号
     *
     * @type {string}
     * @memberof CallNumberInput
     */
    callNumber?: string | null;
}
