/* tslint:disable */
/* eslint-disable */
/**
 * 叫号服务
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 诊室绑定设备
 *
 * @export
 * @interface CallRoomBindDeviceInput
 */
export interface CallRoomBindDeviceInput {

    /**
     * 诊室Id
     *
     * @type {number}
     * @memberof CallRoomBindDeviceInput
     */
    id?: number;

    /**
     * 诊室版本标识
     *
     * @type {string}
     * @memberof CallRoomBindDeviceInput
     */
    ver?: string | null;

    /**
     * 设备表Id
     *
     * @type {number}
     * @memberof CallRoomBindDeviceInput
     */
    deviceSettingId?: number;

    /**
     * 设备标识
     *
     * @type {string}
     * @memberof CallRoomBindDeviceInput
     */
    deviceIdentity?: string | null;
}
