/* tslint:disable */
/* eslint-disable */
/**
 * 会员管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 用户资金详情 账户、会员卡
 *
 * @export
 * @interface CustomerFundDetailsOutput
 */
export interface CustomerFundDetailsOutput {

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof CustomerFundDetailsOutput
     */
    customerId?: number;

    /**
     * 会员次卡 secondarycard、会员卡 memberscard、押金 deposit
     *
     * @type {string}
     * @memberof CustomerFundDetailsOutput
     */
    type?: string | null;

    /**
     * 业务主键Id
     *
     * @type {number}
     * @memberof CustomerFundDetailsOutput
     */
    id?: number;

    /**
     * 总金额 （次卡是余次）
     *
     * @type {number}
     * @memberof CustomerFundDetailsOutput
     */
    totalAmount?: number;

    /**
     * 本金金额  （次卡是本金次数）
     *
     * @type {number}
     * @memberof CustomerFundDetailsOutput
     */
    oriAmount?: number;

    /**
     * 赠送金额  （次卡是赠送次数）
     *
     * @type {number}
     * @memberof CustomerFundDetailsOutput
     */
    giveAmount?: number;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof CustomerFundDetailsOutput
     */
    ver?: string | null;
}
