/* tslint:disable */
/* eslint-disable */
/**
 * 会员管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CustomerSearchForHospitalInput
 */
export interface CustomerSearchForHospitalInput {

    /**
     * 会员名称
     *
     * @type {string}
     * @memberof CustomerSearchForHospitalInput
     */
    name?: string | null;

    /**
     * 手机号码
     *
     * @type {string}
     * @memberof CustomerSearchForHospitalInput
     */
    cellPhone?: string | null;

    /**
     * 会员编号
     *
     * @type {string}
     * @memberof CustomerSearchForHospitalInput
     */
    cardNumber?: string | null;

    /**
     * 宠物名称
     *
     * @type {string}
     * @memberof CustomerSearchForHospitalInput
     */
    petName?: string | null;

    /**
     * 会员级别
     *
     * @type {number}
     * @memberof CustomerSearchForHospitalInput
     */
    level?: number | null;
}
