/* tslint:disable */
/* eslint-disable */
/**
 * 会员管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CustomerSMSOutput
 */
export interface CustomerSMSOutput {

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof CustomerSMSOutput
     */
    id?: number;

    /**
     * 名称
     *
     * @type {string}
     * @memberof CustomerSMSOutput
     */
    name?: string | null;

    /**
     * 用户手机号码
     *
     * @type {string}
     * @memberof CustomerSMSOutput
     */
    cellPhone?: string | null;

    /**
     * 会员级别
     *
     * @type {number}
     * @memberof CustomerSMSOutput
     */
    level?: number;

    /**
     * 会员级别名称
     *
     * @type {string}
     * @memberof CustomerSMSOutput
     */
    levelText?: string | null;

    /**
     * 消费总金额
     *
     * @type {number}
     * @memberof CustomerSMSOutput
     */
    amount?: number;
}
