/* tslint:disable */
/* eslint-disable */
/**
 * 会员管理
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface CustomerPetInfoForSaleInput
 */
export interface CustomerPetInfoForSaleInput {

    /**
     * 用户ID
     *
     * @type {number}
     * @memberof CustomerPetInfoForSaleInput
     */
    customerId?: number;

    /**
     * 宠物ID
     *
     * @type {number}
     * @memberof CustomerPetInfoForSaleInput
     */
    petId?: number;
}
