/* tslint:disable */
/* eslint-disable */
/**
 * 会员管理
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * <br />&nbsp;储值卡 StoredCard = 0<br />&nbsp;次卡 OrderCard = 1<br />
 * @export
 * @enum {string}
 */
export enum MemberCardTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}

