/* tslint:disable */
/* eslint-disable */
/**
 * 会员管理
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 分页查询实体
 *
 * @export
 * @interface PagePcuAccountDto
 */
export interface PagePcuAccountDto {

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof PagePcuAccountDto
     */
    createTime?: Date | null;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof PagePcuAccountDto
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof PagePcuAccountDto
     */
    createUserId?: number | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof PagePcuAccountDto
     */
    updateUserId?: number | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof PagePcuAccountDto
     */
    isDelete?: boolean;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof PagePcuAccountDto
     */
    ver?: string | null;

    /**
     * 创建者部门名称
     *
     * @type {string}
     * @memberof PagePcuAccountDto
     */
    createOrgName?: string | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof PagePcuAccountDto
     */
    updateUserName?: string | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof PagePcuAccountDto
     */
    createUserName?: string | null;

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof PagePcuAccountDto
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof PagePcuAccountDto
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof PagePcuAccountDto
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof PagePcuAccountDto
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof PagePcuAccountDto
     */
    descStr?: string | null;

    /**
     * 用户id
     *
     * @type {number}
     * @memberof PagePcuAccountDto
     */
    customerId?: number;
}
