/* tslint:disable */
/* eslint-disable */
/**
 * 会员管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 快速添加会员及宠物信息
 *
 * @export
 * @interface PcustomerFastInput
 */
export interface PcustomerFastInput {

    /**
     * 会员名称
     *
     * @type {string}
     * @memberof PcustomerFastInput
     */
    name?: string | null;

    /**
     * 会员级别
     *
     * @type {number}
     * @memberof PcustomerFastInput
     */
    level?: number | null;

    /**
     * 客户来源
     *
     * @type {string}
     * @memberof PcustomerFastInput
     */
    sourceid?: string | null;

    /**
     * 手机号
     *
     * @type {string}
     * @memberof PcustomerFastInput
     */
    cellPhone?: string | null;

    /**
     * 性别
     *
     * @type {number}
     * @memberof PcustomerFastInput
     */
    sex?: number;

    /**
     * 会员生日
     *
     * @type {Date}
     * @memberof PcustomerFastInput
     */
    birthdate?: Date;

    /**
     * 宠主id
     *
     * @type {number}
     * @memberof PcustomerFastInput
     */
    customerId?: number;

    /**
     * 宠物名称
     *
     * @type {string}
     * @memberof PcustomerFastInput
     */
    petName?: string | null;

    /**
     * 性别 (0 公 1 母 2 未知)
     *
     * @type {number}
     * @memberof PcustomerFastInput
     */
    petGender?: number;

    /**
     * 生日
     *
     * @type {Date}
     * @memberof PcustomerFastInput
     */
    petBirthDate?: Date | null;

    /**
     * 宠物种类
     *
     * @type {number}
     * @memberof PcustomerFastInput
     */
    petKind?: number;

    /**
     * 宠物品种
     *
     * @type {number}
     * @memberof PcustomerFastInput
     */
    petVarietie?: number;

    /**
     * 宠物血型  -1未知 0 纯种 1 杂交
     *
     * @type {number}
     * @memberof PcustomerFastInput
     */
    petBlood?: number;

    /**
     * 宠物毛色
     *
     * @type {number}
     * @memberof PcustomerFastInput
     */
    petColor?: number;
}
