/* tslint:disable */
/* eslint-disable */
/**
 * 会员管理
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PcuAccountPayMethod } from './pcu-account-pay-method';
import {
    PcuAccountPayMethod,
} from ".";

/**
 * 充值实体
 *
 * @export
 * @interface RechargeAccountDto
 */
export interface RechargeAccountDto {

    /**
     * 交易号R 充值  P 消费  T 退款
     *
     * @type {string}
     * @memberof RechargeAccountDto
     */
    orderNo?: string | null;

    /**
     * 总金额
     *
     * @type {number}
     * @memberof RechargeAccountDto
     */
    amountPrice?: number;

    /**
     * 赠送金额
     *
     * @type {number}
     * @memberof RechargeAccountDto
     */
    givePrice?: number;

    /**
     * 本金金额
     *
     * @type {number}
     * @memberof RechargeAccountDto
     */
    principalPrice?: number;

    /**
     * 发生金额
     *
     * @type {number}
     * @memberof RechargeAccountDto
     */
    occurPrice?: number;

    /**
     * 用户id
     *
     * @type {number}
     * @memberof RechargeAccountDto
     */
    customerId: number;

    /**
     * 账户id
     *
     * @type {number}
     * @memberof RechargeAccountDto
     */
    pcuAccountId?: number;

    /**
     * 账户支付方式
     *
     * @type {Array<PcuAccountPayMethod>}
     * @memberof RechargeAccountDto
     */
    pcuAccountPayMethods?: Array<PcuAccountPayMethod> | null;
}
