/* tslint:disable */
/* eslint-disable */
/**
 * 会员管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Filter } from './filter';
import { Search } from './search';
 /**
 * 
 *
 * @export
 * @interface UpdatePPetsInput
 */
export interface UpdatePPetsInput {

    /**
     * @type {Search}
     * @memberof UpdatePPetsInput
     */
    search?: Search;

    /**
     * 模糊查询关键字
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    keyword?: string | null;

    /**
     * @type {Filter}
     * @memberof UpdatePPetsInput
     */
    filter?: Filter;

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof UpdatePPetsInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof UpdatePPetsInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    descStr?: string | null;

    /**
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    ver?: string | null;

    /**
     * 宠主id
     *
     * @type {number}
     * @memberof UpdatePPetsInput
     */
    customerId?: number;

    /**
     * 宠物名称
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    petName: string;

    /**
     * 英文名
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    fullNamePinyin?: string | null;

    /**
     * 性别 (0 公 1 母 2 未知)
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    petGender?: string | null;

    /**
     * 生日
     *
     * @type {Date}
     * @memberof UpdatePPetsInput
     */
    petBirthDate?: Date | null;

    /**
     * 宠物来家日期
     *
     * @type {Date}
     * @memberof UpdatePPetsInput
     */
    petComeHomeDate?: Date | null;

    /**
     * 宠物种类
     *
     * @type {number}
     * @memberof UpdatePPetsInput
     */
    petKind: number;

    /**
     * 宠物品种
     *
     * @type {number}
     * @memberof UpdatePPetsInput
     */
    petVarietie: number;

    /**
     * 宠物血型  -1未知 0 纯种 1 杂交
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    petBlood?: string | null;

    /**
     * 宠物毛色
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    petColor?: string | null;

    /**
     * 宠物体重
     *
     * @type {number}
     * @memberof UpdatePPetsInput
     */
    petWeight?: number;

    /**
     * 是否绝育 -1 未知 0否 1 是
     *
     * @type {number}
     * @memberof UpdatePPetsInput
     */
    petIsSterilization?: number;

    /**
     * 犬证号码
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    petIdentityNumber?: string | null;

    /**
     * 病历号码
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    petRecordNumber?: string | null;

    /**
     * 药物过敏
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    petDrugAllergy?: string | null;

    /**
     * 已接种疫苗 -1未知 0 否 1 是
     *
     * @type {number}
     * @memberof UpdatePPetsInput
     */
    petIsVaccinated?: number;

    /**
     * 上次疫苗时间
     *
     * @type {Date}
     * @memberof UpdatePPetsInput
     */
    petPrevVaccineDate?: Date | null;

    /**
     * 已驱虫 -1未知 0 否 1 是
     *
     * @type {number}
     * @memberof UpdatePPetsInput
     */
    petIsDeworming?: number;

    /**
     * 上次驱虫时间
     *
     * @type {Date}
     * @memberof UpdatePPetsInput
     */
    petPrevDewormingDate?: Date | null;

    /**
     * 宠物芯片
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    petChip?: string | null;

    /**
     * 宠物照片
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    petImageUrl?: string | null;

    /**
     * 宠物状态 默认饲养中
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    petStatus?: string | null;

    /**
     * 宠物备注
     *
     * @type {string}
     * @memberof UpdatePPetsInput
     */
    petRemark?: string | null;

    /**
     * Id
     *
     * @type {number}
     * @memberof UpdatePPetsInput
     */
    id: number;
}
