/* tslint:disable */
/* eslint-disable */
/**
 * 短信发送
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Filter } from './filter';
import { Search } from './search';
 /**
 * 
 *
 * @export
 * @interface AlreadySendMessageInput
 */
export interface AlreadySendMessageInput {

    /**
     * @type {Search}
     * @memberof AlreadySendMessageInput
     */
    search?: Search;

    /**
     * 模糊查询关键字
     *
     * @type {string}
     * @memberof AlreadySendMessageInput
     */
    keyword?: string | null;

    /**
     * @type {Filter}
     * @memberof AlreadySendMessageInput
     */
    filter?: Filter;

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof AlreadySendMessageInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof AlreadySendMessageInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof AlreadySendMessageInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof AlreadySendMessageInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof AlreadySendMessageInput
     */
    descStr?: string | null;

    /**
     * @type {string}
     * @memberof AlreadySendMessageInput
     */
    ver?: string | null;

    /**
     * 查询开始时间
     *
     * @type {Date}
     * @memberof AlreadySendMessageInput
     */
    startTime?: Date;

    /**
     * 查询结束时间
     *
     * @type {Date}
     * @memberof AlreadySendMessageInput
     */
    endTime?: Date;
}
