/* tslint:disable */
/* eslint-disable */
/**
 * 短信发送
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SendSystemSmsInput
 */
export interface SendSystemSmsInput {

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof SendSystemSmsInput
     */
    customerId?: number;

    /**
     * 用户名称
     *
     * @type {string}
     * @memberof SendSystemSmsInput
     */
    customerName?: string | null;

    /**
     * 手机号码  多个手机号码使用英文逗号隔开
     *
     * @type {string}
     * @memberof SendSystemSmsInput
     */
    mobiles?: string | null;

    /**
     * 短信内容
     *
     * @type {string}
     * @memberof SendSystemSmsInput
     */
    content?: string | null;

    /**
     * 短信模板类型
     *
     * @type {string}
     * @memberof SendSystemSmsInput
     */
    templateType?: string | null;

    /**
     * 短信签名  系统内部计算使用 无需传
     *
     * @type {string}
     * @memberof SendSystemSmsInput
     */
    smsSign?: string | null;

    /**
     * 需要扣减的短信条数
     *
     * @type {number}
     * @memberof SendSystemSmsInput
     */
    count?: number;
}
