/* tslint:disable */
/* eslint-disable */
/**
 * 宠物配置管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateSysPetVarietieInput
 */
export interface UpdateSysPetVarietieInput {

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof UpdateSysPetVarietieInput
     */
    createTime?: Date | null;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof UpdateSysPetVarietieInput
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof UpdateSysPetVarietieInput
     */
    createUserId?: number | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof UpdateSysPetVarietieInput
     */
    updateUserId?: number | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof UpdateSysPetVarietieInput
     */
    isDelete?: boolean;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof UpdateSysPetVarietieInput
     */
    ver?: string | null;

    /**
     * 创建者部门名称
     *
     * @type {string}
     * @memberof UpdateSysPetVarietieInput
     */
    createOrgName?: string | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof UpdateSysPetVarietieInput
     */
    updateUserName?: string | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof UpdateSysPetVarietieInput
     */
    createUserName?: string | null;

    /**
     * 种类名称
     *
     * @type {string}
     * @memberof UpdateSysPetVarietieInput
     */
    name?: string | null;

    /**
     * 序号
     *
     * @type {number}
     * @memberof UpdateSysPetVarietieInput
     */
    order?: number;

    /**
     * 英文名称
     *
     * @type {string}
     * @memberof UpdateSysPetVarietieInput
     */
    englishName?: string | null;

    /**
     * 种类id
     *
     * @type {number}
     * @memberof UpdateSysPetVarietieInput
     */
    kindId?: number;

    /**
     * Id
     *
     * @type {number}
     * @memberof UpdateSysPetVarietieInput
     */
    id?: number;
}
