/* tslint:disable */
/* eslint-disable */
/**
 * 次卡管理
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MemberCardStatusEnum } from './member-card-status-enum';
import { SecondaryCardItemsDto } from './secondary-card-items-dto';
 /**
 * 编辑
 *
 * @export
 * @interface SecondaryCardsEditInput
 */
export interface SecondaryCardsEditInput {

    /**
     * 卡名称
     *
     * @type {string}
     * @memberof SecondaryCardsEditInput
     */
    name?: string | null;

    /**
     * 卡号
     *
     * @type {string}
     * @memberof SecondaryCardsEditInput
     */
    cardNumber?: string | null;

    /**
     * 卡到期时间
     *
     * @type {Date}
     * @memberof SecondaryCardsEditInput
     */
    endTime?: Date | null;

    /**
     * @type {MemberCardStatusEnum}
     * @memberof SecondaryCardsEditInput
     */
    status?: MemberCardStatusEnum;

    /**
     * 总次数
     *
     * @type {number}
     * @memberof SecondaryCardsEditInput
     */
    totalCount?: number;

    /**
     * 本金次数
     *
     * @type {number}
     * @memberof SecondaryCardsEditInput
     */
    principalCount?: number;

    /**
     * 赠送次数
     *
     * @type {number}
     * @memberof SecondaryCardsEditInput
     */
    giftCount?: number;

    /**
     * 销售价格
     *
     * @type {number}
     * @memberof SecondaryCardsEditInput
     */
    salePrice?: number;

    /**
     * 会员价格
     *
     * @type {number}
     * @memberof SecondaryCardsEditInput
     */
    memberPrice?: number;

    /**
     * 备注
     *
     * @type {string}
     * @memberof SecondaryCardsEditInput
     */
    remark?: string | null;

    /**
     * 包含的产品项目
     *
     * @type {Array<SecondaryCardItemsDto>}
     * @memberof SecondaryCardsEditInput
     */
    secondaryCardItems?: Array<SecondaryCardItemsDto> | null;

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof SecondaryCardsEditInput
     */
    id?: number;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof SecondaryCardsEditInput
     */
    ver?: string | null;
}
