/* tslint:disable */
/* eslint-disable */
/**
 * 次卡管理
 * <br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MemberCardStatusEnum } from './member-card-status-enum';
import { SecondaryCardItems } from './secondary-card-items';
 /**
 * 系统次卡
 *
 * @export
 * @interface SecondaryCards
 */
export interface SecondaryCards {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof SecondaryCards
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof SecondaryCards
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof SecondaryCards
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof SecondaryCards
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof SecondaryCards
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof SecondaryCards
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof SecondaryCards
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof SecondaryCards
     */
    isDelete?: boolean;

    /**
     * @type {string}
     * @memberof SecondaryCards
     */
    ver?: string | null;

    /**
     * 创建者部门Id
     *
     * @type {number}
     * @memberof SecondaryCards
     */
    createOrgId?: number | null;

    /**
     * 创建者部门名称
     *
     * @type {string}
     * @memberof SecondaryCards
     */
    createOrgName?: string | null;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof SecondaryCards
     */
    tenantId?: number | null;

    /**
     * 卡名称
     *
     * @type {string}
     * @memberof SecondaryCards
     */
    name?: string | null;

    /**
     * 卡号
     *
     * @type {string}
     * @memberof SecondaryCards
     */
    cardNumber?: string | null;

    /**
     * 卡到期时间
     *
     * @type {Date}
     * @memberof SecondaryCards
     */
    endTime?: Date | null;

    /**
     * @type {MemberCardStatusEnum}
     * @memberof SecondaryCards
     */
    status?: MemberCardStatusEnum;

    /**
     * 总次数
     *
     * @type {number}
     * @memberof SecondaryCards
     */
    totalCount?: number;

    /**
     * 本金次数
     *
     * @type {number}
     * @memberof SecondaryCards
     */
    principalCount?: number;

    /**
     * 赠送次数
     *
     * @type {number}
     * @memberof SecondaryCards
     */
    giftCount?: number;

    /**
     * 销售价格
     *
     * @type {number}
     * @memberof SecondaryCards
     */
    salePrice?: number;

    /**
     * 会员价格
     *
     * @type {number}
     * @memberof SecondaryCards
     */
    memberPrice?: number;

    /**
     * 备注
     *
     * @type {string}
     * @memberof SecondaryCards
     */
    remark?: string | null;

    /**
     * 包含的项目明细
     *
     * @type {Array<SecondaryCardItems>}
     * @memberof SecondaryCards
     */
    secondaryCardsItem?: Array<SecondaryCardItems> | null;
}
