
export default {
    title: 'xxxx病例（个体动物）', 
    a:'√',
    b:'',
    isEmer:'0',
    customerName: '张三',
    customerPhone: '185xxxxxxxx',
    cardNumber:'C0000000001',
    petName: '宠物名称',
    petGenderText: '公',
    serialNumber:'R0000000001',
    petWeight:'0.00Kg',
    petAge:'1年2个月',
    petKindText:'宠物种类',
    petVarietieText:'宠物品种',
    petColorText:'宠物毛色',
    petIdentityNumber:'Q0000001',
    printTime:'2024-10-01 12:00:00',
    createTime:'2024-10-01 12:00:00',
    visitDoctorName:'责任医生',
    orderNo:'BL0000000001',
    regTypeText:'初诊',  
    diagnosesNames:'疾病诊断',
    diagnosesRemark:'诊断描述',
    physicalRemark:'体格检查',
    cemRecordRemark:'化验结果描述',
    cemRecordPrescriptionRemark:'治疗计划',
    prescriptionsHtml:'<p class="html-prescriptions" style="margin:0;font-size:13px">开单时间：2024/08/14 11:01:57</p><table class="cus-table" style="width:100%;table-layout:auto"><thead><tr><th style="letter-spacing:2px;text-align:left;padding:6px 6px 6px 12px">项目名称</th><th style="letter-spacing:2px;text-align:left;padding:6px 6px 6px 12px">单位</th><th style="letter-spacing:2px;text-align:left;padding:6px 6px 6px 12px">规格</th><th style="letter-spacing:2px;text-align:left;padding:6px 6px 6px 12px">单次用量</th><th style="letter-spacing:2px;text-align:left;padding:6px 6px 6px 12px">数量</th><th style="letter-spacing:2px;text-align:left;padding:6px 6px 6px 12px">单价</th><th style="letter-spacing:2px;text-align:left;padding:6px 6px 6px 12px">总金额</th></tr></thead><tbody><tr><td>双氧水</td><td>瓶</td><td>-</td><td>1.0000</td><td>1</td><td>￥2.80</td><td>￥2.80</td></tr><tr><td>碘伏</td><td>瓶</td><td>-</td><td>1.0000</td><td>1</td><td>￥6.20</td><td>￥6.20</td></tr><tr><td>酒精</td><td>瓶</td><td>-</td><td>1.0000</td><td>1</td><td>￥4.64</td><td>￥4.64</td></tr><tr><td>新洁尔灭</td><td>瓶</td><td></td><td>1.0000</td><td>1</td><td>￥3.00</td><td>￥3.00</td></tr><tr><td>氟欣安</td><td>瓶</td><td>1*50ml</td><td>1.0000</td><td>1</td><td>￥2.60</td><td>￥2.60</td></tr><tr><td>奥普乐注射液</td><td>ml</td><td></td><td>1.0000</td><td>1</td><td>￥3.20</td><td>￥3.20</td></tr><tr><td>素高捷疗眼膏</td><td>g</td><td></td><td>1.0000</td><td>1</td><td>￥40.00</td><td>￥40.00</td></tr><tr><td>拜有利针剂100ml</td><td>ml</td><td></td><td>1.0000</td><td>1</td><td>￥2.20</td><td>￥2.20</td></tr><tr><td>赛瑞宁20ml</td><td>ml</td><td></td><td>1.0000</td><td>1</td><td>￥34.00</td><td>￥34.00</td></tr><tr><td>痛立定针</td><td>ml</td><td></td><td>1.0000</td><td>1</td><td>￥1.83</td><td>￥1.83</td></tr><tr><td>2%麻佛微素注射液</td><td>ml</td><td>100ml/瓶</td><td>1.0000</td><td>1</td><td>￥2.60</td><td>￥2.60</td></tr><tr><td>止血宁</td><td>瓶</td><td></td><td>1.0000</td><td>1</td><td>￥30.00</td><td>￥30.00</td></tr><tr><td>通灭</td><td>ml</td><td></td><td>1.0000</td><td>1</td><td>￥3.00</td><td>￥3.00</td></tr><tr><td>科特壮</td><td></td><td></td><td>1.0000</td><td>1</td><td>￥1.80</td><td>￥1.80</td></tr><tr><td>润康滴眼液</td><td>瓶</td><td></td><td>1.0000</td><td>1</td><td>￥17.85</td><td>￥17.85</td></tr><tr><td>维克 眼净125ml</td><td>瓶</td><td>125ml</td><td>1.0000</td><td>1</td><td>￥75.00</td><td>￥75.00</td></tr><tr><td>贝复舒</td><td>瓶</td><td></td><td>1.0000</td><td>1</td><td>￥38.00</td><td>￥38.00</td></tr><tr><td>托百士</td><td>瓶</td><td></td><td>1.0000</td><td>1</td><td>￥26.94</td><td>￥26.94</td></tr><tr><td>百灵金方明目液</td><td>瓶</td><td></td><td>1.0000</td><td>1</td><td>￥20.00</td><td>￥20.00</td></tr><tr><td>acyliovir滴眼液</td><td>瓶</td><td></td><td>1.0000</td><td>1</td><td>￥6.00</td><td>￥6.00</td></tr></tbody></table>',
    zhuSu: {
        zhuSu:'主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉主诉',
        pastHistory:'既往史既往史既往史既往史既往史既往史既往史既往史既往史既往史既往史既往史既往史既往史既往史既往史\n\r既往史既往史既往史既往史既往史既往史',
        allergyHistory:'疾病史疾病史疾病史疾病史疾病史疾病史疾病史疾病史疾病史疾病史疾病史疾病史疾病史疾病史',
    },
    physical:{
        petWeight:'23Kg',
        temperature:'2',
        respiratoryRate:'2',
        crt:'2',
        bcs:'2',
        heartRate:'2',
    },
    prescriptions:[ 
                {billingTime:'2024-07-30 16:39:10',itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {billingTime:'2024-07-30 16:39:10',itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {billingTime:'2024-07-30 16:39:10',itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {billingTime:'2024-07-30 16:39:10',itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {billingTime:'2024-07-30 16:39:10',itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {billingTime:'2024-07-30 16:39:10',itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {billingTime:'2024-07-30 16:39:10',itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {billingTime:'2024-07-30 16:39:10',itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
                {itemName:'氟欣安',typeText:'药品',unitName:'瓶',specific:'1*50ml',useDose:'1',dayNum:'1',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'}, 
    ],
    tests:[
        {billingTime:'2024-07-30 16:39:10',itemName:'氟欣安',typeText:'药品',unitName:'瓶',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
        {billingTime:'2024-07-30 16:39:10',itemName:'氟欣安',typeText:'药品',unitName:'瓶',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
        {billingTime:'2024-07-30 16:39:10',itemName:'氟欣安',typeText:'药品',unitName:'瓶',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
        {billingTime:'2024-07-30 16:39:10',itemName:'氟欣安',typeText:'药品',unitName:'瓶',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
        {billingTime:'2024-07-30 16:39:10',itemName:'氟欣安',typeText:'药品',unitName:'瓶',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'},
        {billingTime:'2024-07-30 16:39:10',itemName:'氟欣安',typeText:'药品',unitName:'瓶',amountCount:'1',count:'1',salePrice:'1',amountPrice:'11'}
    ]
};
