/* tslint:disable */
/* eslint-disable */
/**
 * 出入库明细
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OutOrderTypeEnum } from './out-order-type-enum';

/**
 * 出库明细分页请求参数
 *
 * @export
 * @interface OutStockItemsPageInput
 */
export interface OutStockItemsPageInput {

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof OutStockItemsPageInput
     */
    createTime?: Date | null;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof OutStockItemsPageInput
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof OutStockItemsPageInput
     */
    createUserId?: number | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof OutStockItemsPageInput
     */
    updateUserId?: number | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof OutStockItemsPageInput
     */
    isDelete?: boolean;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof OutStockItemsPageInput
     */
    ver?: string | null;

    /**
     * 创建者部门名称
     *
     * @type {string}
     * @memberof OutStockItemsPageInput
     */
    createOrgName?: string | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof OutStockItemsPageInput
     */
    updateUserName?: string | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof OutStockItemsPageInput
     */
    createUserName?: string | null;

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof OutStockItemsPageInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof OutStockItemsPageInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof OutStockItemsPageInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof OutStockItemsPageInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof OutStockItemsPageInput
     */
    descStr?: string | null;

    /**
     * 产品名称
     *
     * @type {string}
     * @memberof OutStockItemsPageInput
     */
    productName?: string | null;

    /**
     * 编号
     *
     * @type {string}
     * @memberof OutStockItemsPageInput
     */
    serialNumber?: string | null;

    /**
     * 开始时间
     *
     * @type {Date}
     * @memberof OutStockItemsPageInput
     */
    startTime?: Date | null;

    /**
     * 结束时间
     *
     * @type {Date}
     * @memberof OutStockItemsPageInput
     */
    endTime?: Date | null;

    /**
     * @type {OutOrderTypeEnum}
     * @memberof OutStockItemsPageInput
     */
    outType?: OutOrderTypeEnum;
}
