/* tslint:disable */
/* eslint-disable */
/**
 * 病例管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MicroInspectImgDto } from './micro-inspect-img-dto';
 /**
 * 显微镜检查结果
 *
 * @export
 * @interface MicroInspectDto
 */
export interface MicroInspectDto {

    /**
     * 显微镜检查结果Id
     *
     * @type {number}
     * @memberof MicroInspectDto
     */
    id?: number;

    /**
     * 检验项目明细表id（CEMRecordTestItem.Id）
     *
     * @type {number}
     * @memberof MicroInspectDto
     */
    cemRecordTestItemId?: number;

    /**
     * 产品id(product_drugs.id)
     *
     * @type {number}
     * @memberof MicroInspectDto
     */
    itemId?: number;

    /**
     * 产品名称(product_drugs.name)
     *
     * @type {string}
     * @memberof MicroInspectDto
     */
    itemName?: string | null;

    /**
     * 宠物id
     *
     * @type {number}
     * @memberof MicroInspectDto
     */
    petId?: number;

    /**
     * 显微镜检查部位
     *
     * @type {string}
     * @memberof MicroInspectDto
     */
    microInspectPart?: string | null;

    /**
     * 显微镜描述
     *
     * @type {string}
     * @memberof MicroInspectDto
     */
    microDescribe?: string | null;

    /**
     * 显微镜提示
     *
     * @type {string}
     * @memberof MicroInspectDto
     */
    microTips?: string | null;

    /**
     * 显微镜建议
     *
     * @type {string}
     * @memberof MicroInspectDto
     */
    microPropose?: string | null;

    /**
     * 检查医生Id(sys_user.id)
     *
     * @type {number}
     * @memberof MicroInspectDto
     */
    checkDoctorId?: number | null;

    /**
     * 检查医生真实姓名(sys_user.real_name)
     *
     * @type {string}
     * @memberof MicroInspectDto
     */
    checkDoctorName?: string | null;

    /**
     * 检查时间
     *
     * @type {Date}
     * @memberof MicroInspectDto
     */
    checkTime?: Date | null;

    /**
     * 报告医生Id(sys_user.id)
     *
     * @type {number}
     * @memberof MicroInspectDto
     */
    reportDoctorId?: number | null;

    /**
     * 报告医生真实姓名(sys_user.real_name)
     *
     * @type {string}
     * @memberof MicroInspectDto
     */
    reportDoctorName?: string | null;

    /**
     * 报告时间
     *
     * @type {Date}
     * @memberof MicroInspectDto
     */
    reportTime?: Date | null;

    /**
     * 显微镜检查图像列表
     *
     * @type {Array<MicroInspectImgDto>}
     * @memberof MicroInspectDto
     */
    microInspectImgList?: Array<MicroInspectImgDto> | null;
}
