/* tslint:disable */
/* eslint-disable */
/**
 * 病例管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SaveBscanInspectImgInput } from './save-bscan-inspect-img-input';
 /**
 * 保存诊疗超声检查检查项目结果
 *
 * @export
 * @interface SaveBscanInspectInput
 */
export interface SaveBscanInspectInput {

    /**
     * 检验项目明细表id（CEMRecordTestItem.Id）
     *
     * @type {number}
     * @memberof SaveBscanInspectInput
     */
    cemRecordTestItemId?: number;

    /**
     * 超声描述
     *
     * @type {string}
     * @memberof SaveBscanInspectInput
     */
    bscanDescribe?: string | null;

    /**
     * 超声提示
     *
     * @type {string}
     * @memberof SaveBscanInspectInput
     */
    bscanTips?: string | null;

    /**
     * 超声建议
     *
     * @type {string}
     * @memberof SaveBscanInspectInput
     */
    bscanPropose?: string | null;

    /**
     * 检查医生Id(sys_user.id)
     *
     * @type {number}
     * @memberof SaveBscanInspectInput
     */
    checkDoctorId?: number | null;

    /**
     * 检查医生真实姓名(sys_user.real_name)
     *
     * @type {string}
     * @memberof SaveBscanInspectInput
     */
    checkDoctorName?: string | null;

    /**
     * 检查时间
     *
     * @type {Date}
     * @memberof SaveBscanInspectInput
     */
    checkTime?: string | null;

    /**
     * 报告医生Id(sys_user.id)
     *
     * @type {number}
     * @memberof SaveBscanInspectInput
     */
    reportDoctorId?: number | null;

    /**
     * 报告医生真实姓名(sys_user.real_name)
     *
     * @type {string}
     * @memberof SaveBscanInspectInput
     */
    reportDoctorName?: string | null;

    /**
     * 报告时间
     *
     * @type {Date}
     * @memberof SaveBscanInspectInput
     */
    reportTime?: string | null;

    /**
     * 助理Id(sys_user.id)
     *
     * @type {number}
     * @memberof SaveBscanInspectInput
     */
    assistantId?: number | null;

    /**
     * 助理姓名(sys_user.real_name)
     *
     * @type {string}
     * @memberof SaveBscanInspectInput
     */
    assistantName?: string | null;
    /**
     * 诊疗超声检查检查图像
     *
     * @type {Array<SaveBscanInspectImgInput>}
     * @memberof SaveBscanInspectInput
     */
    bscanInspectImgList?: Array<SaveBscanInspectImgInput> | null;
}
