/* tslint:disable */
/* eslint-disable */
/**
 * 订单信息
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MiniMedicalRecordPaymentFileInput
 */
export interface MiniMedicalRecordPaymentFileInput {

    /**
     * 文件名称
     *
     * @type {string}
     * @memberof MiniMedicalRecordPaymentFileInput
     */
    fileName?: string | null;

    /**
     * 后缀名称
     *
     * @type {string}
     * @memberof MiniMedicalRecordPaymentFileInput
     */
    suffixName?: string | null;

    /**
     * 文件路径
     *
     * @type {string}
     * @memberof MiniMedicalRecordPaymentFileInput
     */
    fileUrl?: string | null;

    /**
     * 文件大小
     *
     * @type {number}
     * @memberof MiniMedicalRecordPaymentFileInput
     */
    fileSize?: number;
}
