/* tslint:disable */
/* eslint-disable */
/**
 * 订单信息
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BusinessTypeEnum } from './business-type-enum';
import { PaymentStatusEnum } from './payment-status-enum';
import { ProductCostTypeEnums } from './product-cost-type-enums';
import { ProductTypeEnums } from './product-type-enums';
 /**
 * 
 *
 * @export
 * @interface PaymentDetailsOutput
 */
export interface PaymentDetailsOutput {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    id?: number;

    /**
     * 产品ID
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    productId?: number;

    /**
     * 产品名称
     *
     * @type {string}
     * @memberof PaymentDetailsOutput
     */
    productName?: string | null;

    /**
     * 支付ID
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    paymentId?: number;

    /**
     * @type {ProductCostTypeEnums}
     * @memberof PaymentDetailsOutput
     */
    costType?: ProductCostTypeEnums;

    /**
     * @type {string}
     * @memberof PaymentDetailsOutput
     */
    costTypeText?: string | null;

    /**
     * @type {ProductTypeEnums}
     * @memberof PaymentDetailsOutput
     */
    type?: ProductTypeEnums;

    /**
     * 费用类型名称
     *
     * @type {string}
     * @memberof PaymentDetailsOutput
     */
    costTypeName?: string | null;

    /**
     * 用户ID
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    customerId?: number;

    /**
     * 用户名称
     *
     * @type {string}
     * @memberof PaymentDetailsOutput
     */
    customerName?: string | null;

    /**
     * 宠物ID
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    petId?: number;

    /**
     * 宠物名称
     *
     * @type {string}
     * @memberof PaymentDetailsOutput
     */
    petName?: string | null;

    /**
     * 销售人员ID
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    saleId?: number;

    /**
     * 销售人员名称
     *
     * @type {string}
     * @memberof PaymentDetailsOutput
     */
    saleName?: string | null;

    /**
     * 助理人员ID
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    assistantId?: number | null;

    /**
     * 助理人员名称
     *
     * @type {string}
     * @memberof PaymentDetailsOutput
     */
    assistantName?: string | null;

    /**
     * 购买个数
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    count?: number;

    /**
     * 销售单价
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    salePrice?: number;

    /**
     * 支付单价
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    settlementPrice?: number;

    /**
     * 折扣比率
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    discountRatio?: number;

    /**
     * 实付金额
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    actualPrice?: number;

    /**
     * 成本价格
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    costPrice?: number;

    /**
     * 出库单位ID
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    outUnitId?: number;

    /**
     * 出库单位名称
     *
     * @type {string}
     * @memberof PaymentDetailsOutput
     */
    outUnitName?: string | null;

    /**
     * 组ID  不可为空
     *
     * @type {string}
     * @memberof PaymentDetailsOutput
     */
    groupId?: string;

    /**
     * 是否套餐项目
     *
     * @type {boolean}
     * @memberof PaymentDetailsOutput
     */
    isMeal?: boolean;

    /**
     * 套餐ID
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    mealId?: number;

    /**
     * 是否打包
     *
     * @type {boolean}
     * @memberof PaymentDetailsOutput
     */
    isPackage?: boolean;

    /**
     * 打包ID
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    packageId?: number;

    /**
     * @type {PaymentStatusEnum}
     * @memberof PaymentDetailsOutput
     */
    status?: PaymentStatusEnum;

    /**
     * 状态
     *
     * @type {string}
     * @memberof PaymentDetailsOutput
     */
    statusText?: string | null;

    /**
     * 是否病历单
     *
     * @type {boolean}
     * @memberof PaymentDetailsOutput
     */
    isMedicalRecord?: boolean;

    /**
     * 关联病例ID
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    medicalRecordId?: number;

    /**
     * 下单时间
     *
     * @type {Date}
     * @memberof PaymentDetailsOutput
     */
    placeOrderTime?: Date | null;

    /**
     * 业务id
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    businessId?: number;

    /**
     * @type {BusinessTypeEnum}
     * @memberof PaymentDetailsOutput
     */
    businessType?: BusinessTypeEnum;

    /**
     * 备注
     *
     * @type {string}
     * @memberof PaymentDetailsOutput
     */
    remark?: string | null;

    /**
     * 退单数量
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    returnCount?: number;

    /**
     * 可退个数
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    canReturn?: number;

    /**
     * 是否次卡结算
     *
     * @type {boolean}
     * @memberof PaymentDetailsOutput
     */
    isSecondaryCard?: boolean;

    /**
     * 已退单总金额
     *
     * @type {number}
     * @memberof PaymentDetailsOutput
     */
    returnTotalAmount?: number;

    /**
     * 退款单价  使用逗号分隔  18.21,18.21,18,21
     *
     * @type {string}
     * @memberof PaymentDetailsOutput
     */
    returnUnitPrice?: string | null;

    /**
     * 结算时间
     *
     * @type {Date}
     * @memberof PaymentDetailsOutput
     */
    createTime?: Date | null;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof PaymentDetailsOutput
     */
    ver?: string | null;
}
