/* tslint:disable */
/* eslint-disable */
/**
 * 订单信息
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductCostTypeEnums } from './product-cost-type-enums';
import { ProductTypeEnums } from './product-type-enums';
 /**
 * 
 *
 * @export
 * @interface PaymentCartsForCustomerOutput
 */
export interface PaymentCartsForCustomerOutput {

    /**
     * 购物车ID
     *
     * @type {number}
     * @memberof PaymentCartsForCustomerOutput
     */
    id?: number;

    /**
     * 用户ID
     *
     * @type {number}
     * @memberof PaymentCartsForCustomerOutput
     */
    customerId?: number;

    /**
     * 用户名称
     *
     * @type {string}
     * @memberof PaymentCartsForCustomerOutput
     */
    customerName?: string | null;

    /**
     * 宠物ID
     *
     * @type {number}
     * @memberof PaymentCartsForCustomerOutput
     */
    petId?: number;

    /**
     * 宠物名称
     *
     * @type {string}
     * @memberof PaymentCartsForCustomerOutput
     */
    petName?: string | null;

    /**
     * 产品ID
     *
     * @type {number}
     * @memberof PaymentCartsForCustomerOutput
     */
    productId?: number;

    /**
     * 产品名称
     *
     * @type {string}
     * @memberof PaymentCartsForCustomerOutput
     */
    productName?: string | null;

    /**
     * @type {ProductCostTypeEnums}
     * @memberof PaymentCartsForCustomerOutput
     */
    costType?: ProductCostTypeEnums;

    /**
     * @type {ProductTypeEnums}
     * @memberof PaymentCartsForCustomerOutput
     */
    type?: ProductTypeEnums;

    /**
     * 费用类型名称
     *
     * @type {string}
     * @memberof PaymentCartsForCustomerOutput
     */
    costTypeName?: string | null;

    /**
     * 销售人员ID
     *
     * @type {number}
     * @memberof PaymentCartsForCustomerOutput
     */
    saleId?: number;

    /**
     * 销售人员名称
     *
     * @type {string}
     * @memberof PaymentCartsForCustomerOutput
     */
    saleName?: string | null;

    /**
     * 购买个数
     *
     * @type {number}
     * @memberof PaymentCartsForCustomerOutput
     */
    count?: number;

    /**
     * 折扣比率
     *
     * @type {number}
     * @memberof PaymentCartsForCustomerOutput
     */
    discountRatio?: number;

    /**
     * 销售单价
     *
     * @type {number}
     * @memberof PaymentCartsForCustomerOutput
     */
    salePrice?: number;

    /**
     * 总金额
     *
     * @type {number}
     * @memberof PaymentCartsForCustomerOutput
     */
    amountPrice?: number;

    /**
     * 出库单位ID
     *
     * @type {number}
     * @memberof PaymentCartsForCustomerOutput
     */
    outUnitId?: number | null;

    /**
     * 出库单位名称
     *
     * @type {string}
     * @memberof PaymentCartsForCustomerOutput
     */
    outUnitName?: string | null;

    /**
     * 是否改价
     *
     * @type {boolean}
     * @memberof PaymentCartsForCustomerOutput
     */
    isEdit?: boolean;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof PaymentCartsForCustomerOutput
     */
    ver?: string | null;

    /**
     * 折扣率
     *
     * @type {number}
     * @memberof PaymentCartsForCustomerOutput
     */
    discount?: number;

    /**
     * 实付价格
     *
     * @type {number}
     * @memberof PaymentCartsForCustomerOutput
     */
    actualPrice?: number;
}
