/* tslint:disable */
/* eslint-disable */
/**
 * 订单信息
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 订单状态枚举<br />&nbsp;已支付 AlreadyPaid = 0<br />&nbsp;部分已退款 PartRefunded = 1<br />&nbsp;已退款 Refunded = 2<br />
 * @export
 * @enum {string}
 */
export enum PaymentStatusEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2
}

