/* tslint:disable */
/* eslint-disable */
/**
 * 订单信息
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BusinessTypeEnum } from './business-type-enum';
import { ProductCostTypeEnums } from './product-cost-type-enums';
import { ProductTypeEnums } from './product-type-enums';
 /**
 * 购物车表
 *
 * @export
 * @interface PaymentCarts
 */
export interface PaymentCarts {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof PaymentCarts
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof PaymentCarts
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof PaymentCarts
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof PaymentCarts
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof PaymentCarts
     */
    isDelete?: boolean;

    /**
     * @type {string}
     * @memberof PaymentCarts
     */
    ver?: string | null;

    /**
     * 创建者部门Id
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    createOrgId?: number | null;

    /**
     * 创建者部门名称
     *
     * @type {string}
     * @memberof PaymentCarts
     */
    createOrgName?: string | null;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    tenantId?: number | null;

    /**
     * 产品ID
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    productId?: number;

    /**
     * 产品名称
     *
     * @type {string}
     * @memberof PaymentCarts
     */
    productName?: string | null;

    /**
     * @type {ProductCostTypeEnums}
     * @memberof PaymentCarts
     */
    costType?: ProductCostTypeEnums;

    /**
     * 费用类型名称
     *
     * @type {string}
     * @memberof PaymentCarts
     */
    costTypeName?: string | null;

    /**
     * @type {ProductTypeEnums}
     * @memberof PaymentCarts
     */
    type?: ProductTypeEnums;

    /**
     * 用户ID
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    customerId?: number;

    /**
     * 用户名称
     *
     * @type {string}
     * @memberof PaymentCarts
     */
    customerName?: string | null;

    /**
     * 宠物ID
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    petId?: number;

    /**
     * 宠物名称
     *
     * @type {string}
     * @memberof PaymentCarts
     */
    petName?: string | null;

    /**
     * 销售人员ID
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    saleId?: number;

    /**
     * 销售人员名称
     *
     * @type {string}
     * @memberof PaymentCarts
     */
    saleName?: string | null;

    /**
     * 助理人员ID
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    assistantId?: number | null;

    /**
     * 助理人员名称
     *
     * @type {string}
     * @memberof PaymentCarts
     */
    assistantName?: string | null;

    /**
     * 购买个数
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    count?: number;

    /**
     * 折扣比率
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    discountRatio?: number;

    /**
     * 销售单价
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    salePrice?: number;

    /**
     * 总金额
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    amountPrice?: number;

    /**
     * 出库单位ID
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    outUnitId?: number | null;

    /**
     * 出库单位名称
     *
     * @type {string}
     * @memberof PaymentCarts
     */
    outUnitName?: string | null;

    /**
     * 组ID  不可为空
     *
     * @type {string}
     * @memberof PaymentCarts
     */
    groupId?: string;

    /**
     * 是否套餐项目
     *
     * @type {boolean}
     * @memberof PaymentCarts
     */
    isMeal?: boolean;

    /**
     * 套餐ID
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    mealId?: number;

    /**
     * 是否打包
     *
     * @type {boolean}
     * @memberof PaymentCarts
     */
    isPackage?: boolean;

    /**
     * 打包ID
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    packageId?: number;

    /**
     * 是否挂起
     *
     * @type {boolean}
     * @memberof PaymentCarts
     */
    isPending?: boolean;

    /**
     * 是否改价
     *
     * @type {boolean}
     * @memberof PaymentCarts
     */
    isEditPrice?: boolean;

    /**
     * 是否病历单
     *
     * @type {boolean}
     * @memberof PaymentCarts
     */
    isMedicalRecord?: boolean;

    /**
     * 关联病例ID
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    medicalRecordId?: number;

    /**
     * 业务id
     *
     * @type {number}
     * @memberof PaymentCarts
     */
    businessId?: number;

    /**
     * @type {BusinessTypeEnum}
     * @memberof PaymentCarts
     */
    businessType?: BusinessTypeEnum;

    /**
     * 备注
     *
     * @type {string}
     * @memberof PaymentCarts
     */
    remark?: string | null;

    /**
     * 支付效验码
     *
     * @type {string}
     * @memberof PaymentCarts
     */
    payValidation?: string | null;
}
