/* tslint:disable */
/* eslint-disable */
/**
 * 订单信息
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductCostTypeEnums } from './product-cost-type-enums';
 /**
 * 打印账单明细输出参数
 *
 * @export
 * @interface PrintBillDetailsOutput
 */
export interface PrintBillDetailsOutput {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof PrintBillDetailsOutput
     */
    id?: number;

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof PrintBillDetailsOutput
     */
    customerId?: number;

    /**
     * 宠物Id
     *
     * @type {number}
     * @memberof PrintBillDetailsOutput
     */
    petId?: number;

    /**
     * 宠物名称
     *
     * @type {string}
     * @memberof PrintBillDetailsOutput
     */
    petName?: string | null;

    /**
     * 性别 (公 母 未知)
     *
     * @type {string}
     * @memberof PrintBillDetailsOutput
     */
    petGenderText?: string | null;

    /**
     * 宠物种类别名
     *
     * @type {string}
     * @memberof PrintBillDetailsOutput
     */
    petKindText?: string | null;

    /**
     * 宠物生日
     *
     * @type {Date}
     * @memberof PrintBillDetailsOutput
     */
    petBirthDate?: Date | null;

    /**
     * 年龄
     *
     * @type {string}
     * @memberof PrintBillDetailsOutput
     */
    ageText?: string | null;

    /**
     * 产品ID
     *
     * @type {number}
     * @memberof PrintBillDetailsOutput
     */
    productId?: number;

    /**
     * 产品名称
     *
     * @type {string}
     * @memberof PrintBillDetailsOutput
     */
    productName?: string | null;

    /**
     * @type {ProductCostTypeEnums}
     * @memberof PrintBillDetailsOutput
     */
    costType?: ProductCostTypeEnums;

    /**
     * 费用类型文本
     *
     * @type {string}
     * @memberof PrintBillDetailsOutput
     */
    costTypeText?: string | null;

    /**
     * 购买个数
     *
     * @type {number}
     * @memberof PrintBillDetailsOutput
     */
    count?: number;

    /**
     * 支付单价
     *
     * @type {number}
     * @memberof PrintBillDetailsOutput
     */
    settlementPrice?: number;

    /**
     * 折扣比率
     *
     * @type {number}
     * @memberof PrintBillDetailsOutput
     */
    discountRatio?: number;

    /**
     * 实付金额
     *
     * @type {number}
     * @memberof PrintBillDetailsOutput
     */
    actualPrice?: number;

    /**
     * 下单时间
     *
     * @type {Date}
     * @memberof PrintBillDetailsOutput
     */
    placeOrderTime?: Date | null;
}
