/* tslint:disable */
/* eslint-disable */
/**
 * 订单信息
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 打印账单付款方式输出参数
 *
 * @export
 * @interface PrintBillPayMethodsOutput
 */
export interface PrintBillPayMethodsOutput {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof PrintBillPayMethodsOutput
     */
    id?: number;

    /**
     * 用户ID
     *
     * @type {number}
     * @memberof PrintBillPayMethodsOutput
     */
    customerId?: number;

    /**
     * 支付ID
     *
     * @type {number}
     * @memberof PrintBillPayMethodsOutput
     */
    paymentId?: number;

    /**
     * 支付类型ID
     *
     * @type {number}
     * @memberof PrintBillPayMethodsOutput
     */
    typeId?: number;

    /**
     * 支付类型名称
     *
     * @type {string}
     * @memberof PrintBillPayMethodsOutput
     */
    typeName?: string | null;

    /**
     * 支付金额
     *
     * @type {number}
     * @memberof PrintBillPayMethodsOutput
     */
    amount?: number;

    /**
     * 本金金额
     *
     * @type {number}
     * @memberof PrintBillPayMethodsOutput
     */
    principalAmount?: number;

    /**
     * 赠送金额
     *
     * @type {number}
     * @memberof PrintBillPayMethodsOutput
     */
    giftAmount?: number;

    /**
     * 收款还是退单  0收款 1退款
     *
     * @type {number}
     * @memberof PrintBillPayMethodsOutput
     */
    inOrOut?: number;

    /**
     * 备注
     *
     * @type {string}
     * @memberof PrintBillPayMethodsOutput
     */
    remark?: string | null;
}
