/* tslint:disable */
/* eslint-disable */
/**
 * 订单信息
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * <br />&nbsp;
 * 商品零售费 ShangPin = 0<br />&nbsp;
 * 处方药品费用 ChuChang = 1<br />&nbsp;
 * 美容费用 MeiRong = 2<br />&nbsp;
 * 洗澡费用 XiZao = 3<br />&nbsp;
 * 驱虫费用 QuChong = 4<br />&nbsp;
 * 疫苗费用 YiMiao = 5<br />&nbsp;
 * 住院费用 ZhuYuan = 6<br />&nbsp;
 * 留观费用 JiYang = 7<br />&nbsp;
 * 检验费用 Tests = 8<br />&nbsp;
 * 影像费用 Image = 9<br />&nbsp;
 * 耗材费用 Consumables = 10<br />&nbsp;
 * 处置费用 Disposals = 11<br />&nbsp;
 * 其他费用 Other = 12<br />&nbsp;
 * 挂号费用 Register = 13<br />
 * @export
 * @enum {string}
 */
export enum ProductCostTypeEnums {
    /**
     * 商品零售费 ShangPin = 0
     */
    NUMBER_0 = 0,
    /**
     * 处方药品费用 ChuChang = 1
     */
    NUMBER_1 = 1,
    /**
     * 美容费用 MeiRong = 2
     */
    NUMBER_2 = 2,
    /**
     * 洗澡费用 XiZao = 3
     */
    NUMBER_3 = 3,
    /**
     * 驱虫费用 QuChong = 4
     */
    NUMBER_4 = 4,
    /**
     * 疫苗费用 YiMiao = 5
     */
    NUMBER_5 = 5,
    /**
     * 住院费用 ZhuYuan = 6
     */
    NUMBER_6 = 6,
    /**
     * 留观费用 JiYang = 7
     */
    NUMBER_7 = 7,
    /**
     * 检验费用 Tests = 8
     */
    NUMBER_8 = 8,
    /**
     * 影像费用 Image = 9
     */
    NUMBER_9 = 9,
    /**
     * 耗材费用 Consumables = 10
     */
    NUMBER_10 = 10,
    /**
     * 处置费用 Disposals = 11
     */
    NUMBER_11 = 11,
    /**
     * 其他费用 Other = 12
     */
    NUMBER_12 = 12,
    /**
     * 挂号费用 Register = 13
     */
    NUMBER_13 = 13,

}

