/* tslint:disable */
/* eslint-disable */
/**
 * 产品管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Filter } from './filter';
import { ProductTypeEnums } from './product-type-enums';
import { Search } from './search';
 /**
 * 
 *
 * @export
 * @interface AddProductCategorysInput
 */
export interface AddProductCategorysInput {

    /**
     * @type {Search}
     * @memberof AddProductCategorysInput
     */
    search?: Search;

    /**
     * 模糊查询关键字
     *
     * @type {string}
     * @memberof AddProductCategorysInput
     */
    keyword?: string | null;

    /**
     * @type {Filter}
     * @memberof AddProductCategorysInput
     */
    filter?: Filter;

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof AddProductCategorysInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof AddProductCategorysInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof AddProductCategorysInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof AddProductCategorysInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof AddProductCategorysInput
     */
    descStr?: string | null;

    /**
     * @type {string}
     * @memberof AddProductCategorysInput
     */
    ver?: string | null;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof AddProductCategorysInput
     */
    tenantId?: number;

    /**
     * @type {ProductTypeEnums}
     * @memberof AddProductCategorysInput
     */
    categoryType?: ProductTypeEnums;

    /**
     * 目录名称
     *
     * @type {string}
     * @memberof AddProductCategorysInput
     */
    name?: string | null;

    /**
     * 父级id 为0则为根基目录
     *
     * @type {number}
     * @memberof AddProductCategorysInput
     */
    parentId?: number;

    /**
     * 排序列 不可为空
     *
     * @type {number}
     * @memberof AddProductCategorysInput
     */
    sortIndex?: number;

    /**
     * 总部编码
     *
     * @type {string}
     * @memberof AddProductCategorysInput
     */
    serialNumber?: string | null;

    /**
     * 创建者部门Id
     *
     * @type {number}
     * @memberof AddProductCategorysInput
     */
    createOrgId?: number;
}
