/* tslint:disable */
/* eslint-disable */
/**
 * 产品管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductTypeEnums } from './product-type-enums';
 /**
 * 化验/显微镜 检查明细关联表
 *
 * @export
 * @interface ProductMedicationInspectionDetails
 */
export interface ProductMedicationInspectionDetails {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof ProductMedicationInspectionDetails
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof ProductMedicationInspectionDetails
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof ProductMedicationInspectionDetails
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof ProductMedicationInspectionDetails
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof ProductMedicationInspectionDetails
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof ProductMedicationInspectionDetails
     */
    isDelete?: boolean;

    /**
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    ver?: string | null;

    /**
     * 创建者部门Id
     *
     * @type {number}
     * @memberof ProductMedicationInspectionDetails
     */
    createOrgId?: number | null;

    /**
     * 创建者部门名称
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    createOrgName?: string | null;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof ProductMedicationInspectionDetails
     */
    tenantId?: number | null;

    /**
     * 项目名称
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    name?: string | null;

    /**
     * 中文名称
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    chName?: string | null;

    /**
     * 单位
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    unit?: string | null;

    /**
     * 临床意义
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    remark?: string | null;

    /**
     * 狗 最大值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    dogMax?: string | null;

    /**
     * 狗 最小值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    dogMin?: string | null;

    /**
     * 幼年 狗 最大值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    youngDogMax?: string | null;

    /**
     * 幼年 狗 最小值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    youngDogMin?: string | null;

    /**
     * 老年 狗 最大值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    oldDogMax?: string | null;

    /**
     * 老年 狗 最小值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    oldDogMin?: string | null;

    /**
     * 猫 最大值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    catMax?: string | null;

    /**
     * 猫 最小值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    catMin?: string | null;

    /**
     * 幼年 猫 最大值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    youngCatMax?: string | null;

    /**
     * 幼年 猫 最小值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    youngCatMin?: string | null;

    /**
     * 老年 猫 最大值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    oldCatMax?: string | null;

    /**
     * 老年 猫 最小值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    oldCatMin?: string | null;

    /**
     * 其他 最大值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    otherMax?: string | null;

    /**
     * 其他 最小值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    otherMin?: string | null;

    /**
     * 幼年 其他 最大值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    youngOtherMax?: string | null;

    /**
     * 幼年 其他 最小值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    youngOtherMin?: string | null;

    /**
     * 老年 其他 最大值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    oldOtherMax?: string | null;

    /**
     * 老年 其他 最小值
     *
     * @type {string}
     * @memberof ProductMedicationInspectionDetails
     */
    oldOtherMin?: string | null;

    /**
     * 项目明细自身 id  此表为复制的数据
     *
     * @type {number}
     * @memberof ProductMedicationInspectionDetails
     */
    productInspectionDetailsId?: number;

    /**
     * 产品 化验/显微镜 ID
     *
     * @type {number}
     * @memberof ProductMedicationInspectionDetails
     */
    productId?: number;

    /**
     * @type {ProductTypeEnums}
     * @memberof ProductMedicationInspectionDetails
     */
    productType?: ProductTypeEnums;
}
