/* tslint:disable */
/* eslint-disable */
/**
 * 产品管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Filter } from './filter';
import { Search } from './search';
 /**
 * 美容输入参数
 *
 * @export
 * @interface ProductCosmetologysInput
 */
export interface ProductCosmetologysInput {

    /**
     * @type {Search}
     * @memberof ProductCosmetologysInput
     */
    search?: Search;

    /**
     * 模糊查询关键字
     *
     * @type {string}
     * @memberof ProductCosmetologysInput
     */
    keyword?: string | null;

    /**
     * @type {Filter}
     * @memberof ProductCosmetologysInput
     */
    filter?: Filter;

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof ProductCosmetologysInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof ProductCosmetologysInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof ProductCosmetologysInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof ProductCosmetologysInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof ProductCosmetologysInput
     */
    descStr?: string | null;

    /**
     * @type {string}
     * @memberof ProductCosmetologysInput
     */
    ver?: string | null;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof ProductCosmetologysInput
     */
    tenantId?: number | null;

    /**
     * 名称
     *
     * @type {string}
     * @memberof ProductCosmetologysInput
     */
    name?: string | null;

    /**
     * 目录ID
     *
     * @type {number}
     * @memberof ProductCosmetologysInput
     */
    categoryId?: number;

    /**
     * 目录名称
     *
     * @type {string}
     * @memberof ProductCosmetologysInput
     */
    categoryName?: string | null;

    /**
     * 条形码
     *
     * @type {string}
     * @memberof ProductCosmetologysInput
     */
    barCode?: string | null;

    /**
     * 总部编码
     *
     * @type {string}
     * @memberof ProductCosmetologysInput
     */
    serialNumber?: string | null;

    /**
     * 缩写
     *
     * @type {string}
     * @memberof ProductCosmetologysInput
     */
    nameLetter?: string | null;

    /**
     * 英文名称
     *
     * @type {string}
     * @memberof ProductCosmetologysInput
     */
    englishName?: string | null;

    /**
     * 通用名称
     *
     * @type {string}
     * @memberof ProductCosmetologysInput
     */
    commonName?: string | null;

    /**
     * 销售价格
     *
     * @type {number}
     * @memberof ProductCosmetologysInput
     */
    salePrice?: number;

    /**
     * 会员价格
     *
     * @type {number}
     * @memberof ProductCosmetologysInput
     */
    memberPrice?: number;

    /**
     * 是否参与打折
     *
     * @type {boolean}
     * @memberof ProductCosmetologysInput
     */
    isDiscount?: boolean;

    /**
     * 投药单位ID
     *
     * @type {number}
     * @memberof ProductCosmetologysInput
     */
    outUnitId?: number;

    /**
     * 注意事项
     *
     * @type {string}
     * @memberof ProductCosmetologysInput
     */
    notice?: string | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof ProductCosmetologysInput
     */
    remark?: string | null;

    /**
     * 是否允许零库存
     *
     * @type {boolean}
     * @memberof ProductCosmetologysInput
     */
    isZeroSale?: boolean;

    /**
     * 可销
     *
     * @type {boolean}
     * @memberof ProductCosmetologysInput
     */
    canSale?: boolean;

    /**
     * 可订
     *
     * @type {boolean}
     * @memberof ProductCosmetologysInput
     */
    canOrder?: boolean;
}
