/* tslint:disable */
/* eslint-disable */
/**
 * 产品管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductDosings } from './product-dosings';
import { ProductMedicationInspectionDetails } from './product-medication-inspection-details';
import { ProductMedicationRelations } from './product-medication-relations';
import { ProductTestStripResults } from './product-test-strip-results';
import { ProductTypeEnums } from './product-type-enums';
 /**
 * 药品表
 *
 * @export
 * @interface ProductDrugs
 */
export interface ProductDrugs {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof ProductDrugs
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof ProductDrugs
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof ProductDrugs
     */
    isDelete?: boolean;

    /**
     * @type {string}
     * @memberof ProductDrugs
     */
    ver?: string | null;

    /**
     * 创建者部门Id
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    createOrgId?: number | null;

    /**
     * 创建者部门名称
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    createOrgName?: string | null;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    tenantId?: number | null;

    /**
     * 名称
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    name?: string | null;

    /**
     * @type {ProductTypeEnums}
     * @memberof ProductDrugs
     */
    type?: ProductTypeEnums;

    /**
     * @type {string}
     * @memberof ProductDrugs
     */
    typeText?: string | null;

    /**
     * 目录ID
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    categoryId?: number;

    /**
     * 目录名称
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    categoryName?: string | null;

    /**
     * 条形码
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    barCode?: string | null;

    /**
     * 供应商ID
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    providerId?: number;

    /**
     * 生产商ID
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    manufacturerId?: number;

    /**
     * 总部编码
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    serialNumber?: string | null;

    /**
     * 成分
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    ingredient?: string | null;

    /**
     * 缩写
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    nameLetter?: string | null;

    /**
     * 英文名称
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    englishName?: string | null;

    /**
     * 通用名称
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    commonName?: string | null;

    /**
     * 使用方式
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    usingMethod?: number;

    /**
     * 投药方式
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    dosingWay?: number;

    /**
     * 是麻醉药
     *
     * @type {boolean}
     * @memberof ProductDrugs
     */
    isAnaesthesia?: boolean;

    /**
     * 库存个数
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    count?: number;

    /**
     * 成本价
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    costPrice?: number;

    /**
     * 销售价格
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    salePrice?: number;

    /**
     * 会员价格
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    memberPrice?: number;

    /**
     * 是否参与打折
     *
     * @type {boolean}
     * @memberof ProductDrugs
     */
    isDiscount?: boolean;

    /**
     * 是否允许零库存
     *
     * @type {boolean}
     * @memberof ProductDrugs
     */
    isZeroSale?: boolean;

    /**
     * 入库单位ID
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    inUnitId?: number;

    /**
     * 投药单位ID
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    outUnitId?: number;

    /**
     * 入库转换因子
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    inSpecific?: number;

    /**
     * 品牌ID
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    brandId?: number;

    /**
     * 规格
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    specific?: string | null;

    /**
     * 注意事项
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    notice?: string | null;

    /**
     * 性状
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    characters?: string | null;

    /**
     * 适用对象
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    forr?: string | null;

    /**
     * 适应症
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    indication?: string | null;

    /**
     * 药品相互作用
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    drugInteractions?: string | null;

    /**
     * 禁忌
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    taboo?: string | null;

    /**
     * 不良反应
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    adverseReactions?: string | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    remark?: string | null;

    /**
     * 可销
     *
     * @type {boolean}
     * @memberof ProductDrugs
     */
    canSale?: boolean;

    /**
     * 可订
     *
     * @type {boolean}
     * @memberof ProductDrugs
     */
    canOrder?: boolean;

    /**
     * 可盘
     *
     * @type {boolean}
     * @memberof ProductDrugs
     */
    canCable?: boolean;

    /**
     * 停用
     *
     * @type {boolean}
     * @memberof ProductDrugs
     */
    isDisable?: boolean;

    /**
     * 标识id
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    tagId?: number | null;

    /**
     * 标识名称
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    tagName?: string | null;

    /**
     * 接种间隔
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    interval?: number;

    /**
     * 接种间隔单位 Day Week Month Year
     *
     * @type {string}
     * @memberof ProductDrugs
     */
    intervalUnit?: string | null;

    /**
     * 接种次数
     *
     * @type {number}
     * @memberof ProductDrugs
     */
    times?: number;

    /**
     * 种类投药
     *
     * @type {Array<ProductDosings>}
     * @memberof ProductDrugs
     */
    productDosings?: Array<ProductDosings> | null;

    /**
     * 化验/显微镜 检查项目明细
     *
     * @type {Array<ProductMedicationInspectionDetails>}
     * @memberof ProductDrugs
     */
    productMedicationInspectionDetails?: Array<ProductMedicationInspectionDetails> | null;

    /**
     * 处置/化验/显微镜  关联  消耗品/试纸
     *
     * @type {Array<ProductMedicationRelations>}
     * @memberof ProductDrugs
     */
    productMedicationRelations?: Array<ProductMedicationRelations> | null;

    /**
     * 试纸检查结构
     *
     * @type {Array<ProductTestStripResults>}
     * @memberof ProductDrugs
     */
    productTestStripResults?: Array<ProductTestStripResults> | null;
}
