/* tslint:disable */
/* eslint-disable */
/**
 * 产品管理
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 留观表
 * @export
 * @interface ProductFosters
 */
export interface ProductFosters {
    /**
     * 雪花Id
     * @type {number}
     * @memberof ProductFosters
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof ProductFosters
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof ProductFosters
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof ProductFosters
     */
    createUserId?: number | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof ProductFosters
     */
    updateUserId?: number | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof ProductFosters
     */
    isDelete?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductFosters
     */
    ver?: string | null;
    /**
     * 创建者部门Id
     * @type {number}
     * @memberof ProductFosters
     */
    createOrgId?: number | null;
    /**
     * 租户Id
     * @type {number}
     * @memberof ProductFosters
     */
    tenantId?: number | null;
    /**
     * 名称
     * @type {string}
     * @memberof ProductFosters
     */
    name?: string | null;
    /**
     * 产品类型
     * @type {string}
     * @memberof ProductFosters
     */
    type?: string | null;
    /**
     * 目录ID
     * @type {number}
     * @memberof ProductFosters
     */
    categoryId?: number;
    /**
     * 目录名称
     * @type {string}
     * @memberof ProductFosters
     */
    categoryName?: string | null;
    /**
     * 条形码
     * @type {string}
     * @memberof ProductFosters
     */
    barCode?: string | null;
    /**
     * 总部编码
     * @type {string}
     * @memberof ProductFosters
     */
    serialNumber?: string | null;
    /**
     * 缩写
     * @type {string}
     * @memberof ProductFosters
     */
    nameLetter?: string | null;
    /**
     * 英文名称
     * @type {string}
     * @memberof ProductFosters
     */
    englishName?: string | null;
    /**
     * 通用名称
     * @type {string}
     * @memberof ProductFosters
     */
    commonName?: string | null;
    /**
     * 销售价格
     * @type {number}
     * @memberof ProductFosters
     */
    salePrice?: number;
    /**
     * 会员价格
     * @type {number}
     * @memberof ProductFosters
     */
    memberPrice?: number;
    /**
     * 是否参与打折
     * @type {boolean}
     * @memberof ProductFosters
     */
    isDiscount?: boolean;
    /**
     * 投药单位ID
     * @type {number}
     * @memberof ProductFosters
     */
    outUnitId?: number;
    /**
     * 备注
     * @type {string}
     * @memberof ProductFosters
     */
    remark?: string | null;
    /**
     * 注意事项
     * @type {string}
     * @memberof ProductFosters
     */
    notice?: string | null;
}
