/* tslint:disable */
/* eslint-disable */
/**
 * 产品管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ProductBModesDto
 */
export interface ProductBModesDto {

    /**
     * Id
     *
     * @type {number}
     * @memberof ProductBModesDto
     */
    id?: number;

    /**
     * 产品类型
     *
     * @type {string}
     * @memberof ProductBModesDto
     */
    type?: string | null;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof ProductBModesDto
     */
    tenantId?: number | null;

    /**
     * 名称
     *
     * @type {string}
     * @memberof ProductBModesDto
     */
    name?: string | null;

    /**
     * 目录ID
     *
     * @type {number}
     * @memberof ProductBModesDto
     */
    categoryId?: number;

    /**
     * 目录名称
     *
     * @type {string}
     * @memberof ProductBModesDto
     */
    categoryName?: string | null;

    /**
     * 条形码
     *
     * @type {string}
     * @memberof ProductBModesDto
     */
    barCode?: string | null;

    /**
     * 总部编码
     *
     * @type {string}
     * @memberof ProductBModesDto
     */
    serialNumber?: string | null;

    /**
     * 缩写
     *
     * @type {string}
     * @memberof ProductBModesDto
     */
    nameLetter?: string | null;

    /**
     * 英文名称
     *
     * @type {string}
     * @memberof ProductBModesDto
     */
    englishName?: string | null;

    /**
     * 通用名称
     *
     * @type {string}
     * @memberof ProductBModesDto
     */
    commonName?: string | null;

    /**
     * 销售价格
     *
     * @type {number}
     * @memberof ProductBModesDto
     */
    salePrice?: number;

    /**
     * 会员价格
     *
     * @type {number}
     * @memberof ProductBModesDto
     */
    memberPrice?: number;

    /**
     * 是否参与打折
     *
     * @type {boolean}
     * @memberof ProductBModesDto
     */
    isDiscount?: boolean;

    /**
     * 可销
     *
     * @type {boolean}
     * @memberof ProductBModesDto
     */
    canSale?: boolean;

    /**
     * 投药单位ID
     *
     * @type {number}
     * @memberof ProductBModesDto
     */
    outUnitId?: number;

    /**
     * 投药单位名称
     *
     * @type {string}
     * @memberof ProductBModesDto
     */
    outUnitName?: string | null;

    /**
     * 注意事项
     *
     * @type {string}
     * @memberof ProductBModesDto
     */
    notice?: string | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof ProductBModesDto
     */
    remark?: string | null;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof ProductBModesDto
     */
    ver?: string | null;
}
