/* tslint:disable */
/* eslint-disable */
/**
 * 产品管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductCategorysHierarchyDto } from './product-categorys-hierarchy-dto';
 /**
 * 
 *
 * @export
 * @interface ProductCategorysHierarchyDto
 */
export interface ProductCategorysHierarchyDto {

    /**
     * Id
     *
     * @type {number}
     * @memberof ProductCategorysHierarchyDto
     */
    id?: number;

    /**
     * 目录名称
     *
     * @type {string}
     * @memberof ProductCategorysHierarchyDto
     */
    label?: string | null;

    /**
     * 父级id 为0则为根基目录
     *
     * @type {number}
     * @memberof ProductCategorysHierarchyDto
     */
    parentId?: number;

    /**
     * @type {string}
     * @memberof ProductCategorysHierarchyDto
     */
    name?: string | null;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof ProductCategorysHierarchyDto
     */
    ver?: string | null;

    /**
     * @type {number}
     * @memberof ProductCategorysHierarchyDto
     */
    tenantId?: number | null;

    /**
     * 子集集合
     *
     * @type {Array<ProductCategorysHierarchyDto>}
     * @memberof ProductCategorysHierarchyDto
     */
    children?: Array<ProductCategorysHierarchyDto> | null;
}
