/* tslint:disable */
/* eslint-disable */
/**
 * 产品管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductRegistersOutput } from './product-registers-output';
 /**
 * 分页泛型集合
 *
 * @export
 * @interface SqlSugarPagedListProductRegistersOutput
 */
export interface SqlSugarPagedListProductRegistersOutput {

    /**
     * 页码
     *
     * @type {number}
     * @memberof SqlSugarPagedListProductRegistersOutput
     */
    page?: number;

    /**
     * 页容量
     *
     * @type {number}
     * @memberof SqlSugarPagedListProductRegistersOutput
     */
    pageSize?: number;

    /**
     * 总条数
     *
     * @type {number}
     * @memberof SqlSugarPagedListProductRegistersOutput
     */
    total?: number;

    /**
     * 总页数
     *
     * @type {number}
     * @memberof SqlSugarPagedListProductRegistersOutput
     */
    totalPages?: number;

    /**
     * 当前页集合
     *
     * @type {Array<ProductRegistersOutput>}
     * @memberof SqlSugarPagedListProductRegistersOutput
     */
    items?: Array<ProductRegistersOutput> | null;

    /**
     * 是否有上一页
     *
     * @type {boolean}
     * @memberof SqlSugarPagedListProductRegistersOutput
     */
    hasPrevPage?: boolean;

    /**
     * 是否有下一页
     *
     * @type {boolean}
     * @memberof SqlSugarPagedListProductRegistersOutput
     */
    hasNextPage?: boolean;
}
