/* tslint:disable */
/* eslint-disable */
/**
 * 产品管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Filter } from './filter';
import { ProductDosings } from './product-dosings';
import { ProductTypeEnums } from './product-type-enums';
import { Search } from './search';
 /**
 * 
 *
 * @export
 * @interface UpdateProductWashsInput
 */
export interface UpdateProductWashsInput {

    /**
     * @type {Search}
     * @memberof UpdateProductWashsInput
     */
    search?: Search;

    /**
     * 模糊查询关键字
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    keyword?: string | null;

    /**
     * @type {Filter}
     * @memberof UpdateProductWashsInput
     */
    filter?: Filter;

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    descStr?: string | null;

    /**
     * @type {ProductTypeEnums}
     * @memberof UpdateProductWashsInput
     */
    type?: ProductTypeEnums;

    /**
     * 产品类型
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    typeText?: string | null;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    tenantId?: number;

    /**
     * 名称
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    name?: string | null;

    /**
     * 目录ID
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    categoryId?: number;

    /**
     * 目录名称
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    categoryName?: string | null;

    /**
     * 条形码
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    barCode?: string | null;

    /**
     * 供应商ID
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    providerId?: number;

    /**
     * 供应商名称
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    providerName?: string | null;

    /**
     * 生产商ID
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    manufacturerId?: number;

    /**
     * 生产商名称
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    manufacturerName?: string | null;

    /**
     * 成分
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    ingredient?: string | null;

    /**
     * 缩写
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    nameLetter?: string | null;

    /**
     * 英文名称
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    englishName?: string | null;

    /**
     * 通用名称
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    commonName?: string | null;

    /**
     * 使用方式
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    usingMethod?: number;

    /**
     * 投药方式
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    dosingWay?: number;

    /**
     * 有无批次
     *
     * @type {boolean}
     * @memberof UpdateProductWashsInput
     */
    isAnaesthesia?: boolean;

    /**
     * 库存个数
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    count?: number;

    /**
     * 成本价
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    costPrice?: number;

    /**
     * 销售价格
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    salePrice?: number;

    /**
     * 会员价格
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    memberPrice?: number;

    /**
     * 编码
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    serialNumber?: string | null;

    /**
     * 是否参与打折
     *
     * @type {boolean}
     * @memberof UpdateProductWashsInput
     */
    isDiscount?: boolean;

    /**
     * 是否允许零库存
     *
     * @type {boolean}
     * @memberof UpdateProductWashsInput
     */
    isZeroSale?: boolean;

    /**
     * 可销
     *
     * @type {boolean}
     * @memberof UpdateProductWashsInput
     */
    canSale?: boolean;

    /**
     * 可订
     *
     * @type {boolean}
     * @memberof UpdateProductWashsInput
     */
    canOrder?: boolean;

    /**
     * 入库单位ID
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    inUnitId?: number;

    /**
     * 入库单位ID
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    inUnitName?: string | null;

    /**
     * 投药单位ID
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    outUnitId?: number;

    /**
     * 投药单位名称
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    outUnitName?: string | null;

    /**
     * 入库转换因子
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    inSpecific?: number;

    /**
     * 品牌ID
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    brandId?: number;

    /**
     * 品牌名称
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    brandName?: string | null;

    /**
     * 规格
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    specific?: string | null;

    /**
     * 注意事项
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    notice?: string | null;

    /**
     * 性状
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    characters?: string | null;

    /**
     * 适用对象
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    forr?: string | null;

    /**
     * 适应症
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    indication?: string | null;

    /**
     * 药品相互作用
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    drugInteractions?: string | null;

    /**
     * 禁忌
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    taboo?: string | null;

    /**
     * 不良反应
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    adverseReactions?: string | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    remark?: string | null;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    ver?: string | null;

    /**
     * 可盘
     *
     * @type {boolean}
     * @memberof UpdateProductWashsInput
     */
    canCable?: boolean;

    /**
     * 停用
     *
     * @type {boolean}
     * @memberof UpdateProductWashsInput
     */
    isDisable?: boolean;

    /**
     * 标识id
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    tagId?: number | null;

    /**
     * 标识名称
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    tagName?: string | null;

    /**
     * 接种间隔
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    interval?: number;

    /**
     * 接种间隔单位 Day Week Month Year
     *
     * @type {string}
     * @memberof UpdateProductWashsInput
     */
    intervalUnit?: string | null;

    /**
     * 接种次数
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    times?: number;

    /**
     * 种类投药
     *
     * @type {Array<ProductDosings>}
     * @memberof UpdateProductWashsInput
     */
    productDosings?: Array<ProductDosings> | null;

    /**
     * Id
     *
     * @type {number}
     * @memberof UpdateProductWashsInput
     */
    id: number;
}
