/* tslint:disable */
/* eslint-disable */
/**
 * 产品管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductMedicationRelations } from './product-medication-relations';
import { ProductTypeEnums } from './product-type-enums';
 /**
 * 
 *
 * @export
 * @interface UpdateProductDisposalInput
 */
export interface UpdateProductDisposalInput {

    /**
     * @type {ProductTypeEnums}
     * @memberof UpdateProductDisposalInput
     */
    type?: ProductTypeEnums;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof UpdateProductDisposalInput
     */
    tenantId?: number;

    /**
     * 名称
     *
     * @type {string}
     * @memberof UpdateProductDisposalInput
     */
    name?: string | null;

    /**
     * 目录ID
     *
     * @type {number}
     * @memberof UpdateProductDisposalInput
     */
    categoryId?: number;

    /**
     * 目录名称
     *
     * @type {string}
     * @memberof UpdateProductDisposalInput
     */
    categoryName?: string | null;

    /**
     * 条形码
     *
     * @type {string}
     * @memberof UpdateProductDisposalInput
     */
    barCode?: string | null;

    /**
     * 缩写
     *
     * @type {string}
     * @memberof UpdateProductDisposalInput
     */
    nameLetter?: string | null;

    /**
     * 英文名称
     *
     * @type {string}
     * @memberof UpdateProductDisposalInput
     */
    englishName?: string | null;

    /**
     * 通用名称
     *
     * @type {string}
     * @memberof UpdateProductDisposalInput
     */
    commonName?: string | null;

    /**
     * 库存个数
     *
     * @type {number}
     * @memberof UpdateProductDisposalInput
     */
    count?: number;

    /**
     * 成本价
     *
     * @type {number}
     * @memberof UpdateProductDisposalInput
     */
    costPrice?: number;

    /**
     * 销售价格
     *
     * @type {number}
     * @memberof UpdateProductDisposalInput
     */
    salePrice?: number;

    /**
     * 会员价格
     *
     * @type {number}
     * @memberof UpdateProductDisposalInput
     */
    memberPrice?: number;

    /**
     * 编码
     *
     * @type {string}
     * @memberof UpdateProductDisposalInput
     */
    serialNumber?: string | null;

    /**
     * 是否参与打折
     *
     * @type {boolean}
     * @memberof UpdateProductDisposalInput
     */
    isDiscount?: boolean;

    /**
     * 是否允许零库存
     *
     * @type {boolean}
     * @memberof UpdateProductDisposalInput
     */
    isZeroSale?: boolean;

    /**
     * 可销
     *
     * @type {boolean}
     * @memberof UpdateProductDisposalInput
     */
    canSale?: boolean;

    /**
     * 可订
     *
     * @type {boolean}
     * @memberof UpdateProductDisposalInput
     */
    canOrder?: boolean;

    /**
     * 投药单位ID
     *
     * @type {number}
     * @memberof UpdateProductDisposalInput
     */
    outUnitId?: number;

    /**
     * 投药单位名称
     *
     * @type {string}
     * @memberof UpdateProductDisposalInput
     */
    outUnitName?: string | null;

    /**
     * 注意事项
     *
     * @type {string}
     * @memberof UpdateProductDisposalInput
     */
    notice?: string | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof UpdateProductDisposalInput
     */
    remark?: string | null;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof UpdateProductDisposalInput
     */
    ver?: string | null;

    /**
     * 可盘
     *
     * @type {boolean}
     * @memberof UpdateProductDisposalInput
     */
    canCable?: boolean;

    /**
     * 停用
     *
     * @type {boolean}
     * @memberof UpdateProductDisposalInput
     */
    isDisable?: boolean;

    /**
     * 标识id
     *
     * @type {number}
     * @memberof UpdateProductDisposalInput
     */
    tagId?: number | null;

    /**
     * 标识名称
     *
     * @type {string}
     * @memberof UpdateProductDisposalInput
     */
    tagName?: string | null;

    /**
     * 关联项目
     *
     * @type {Array<ProductMedicationRelations>}
     * @memberof UpdateProductDisposalInput
     */
    productMedicationRelations?: Array<ProductMedicationRelations> | null;

    /**
     * Id
     *
     * @type {number}
     * @memberof UpdateProductDisposalInput
     */
    id: number;
}
