/* tslint:disable */
/* eslint-disable */
/**
 * 产品管理
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductTestStripResults } from './product-test-strip-results';
 /**
 * 
 *
 * @export
 * @interface UpdateProductPaperInput
 */
export interface UpdateProductPaperInput {

    /**
     * 产品类型
     *
     * @type {string}
     * @memberof UpdateProductPaperInput
     */
    type?: string | null;

    /**
     * 商品名称
     *
     * @type {string}
     * @memberof UpdateProductPaperInput
     */
    name?: string | null;

    /**
     * 目录ID
     *
     * @type {number}
     * @memberof UpdateProductPaperInput
     */
    categoryId?: number;

    /**
     * 目录名称
     *
     * @type {string}
     * @memberof UpdateProductPaperInput
     */
    categoryName?: string | null;

    /**
     * 可盘
     *
     * @type {boolean}
     * @memberof UpdateProductPaperInput
     */
    canCable?: boolean;

    /**
     * 条形码
     *
     * @type {string}
     * @memberof UpdateProductPaperInput
     */
    barCode?: string | null;

    /**
     * 产品编码
     *
     * @type {string}
     * @memberof UpdateProductPaperInput
     */
    serialNumber?: string | null;

    /**
     * 供应商ID
     *
     * @type {number}
     * @memberof UpdateProductPaperInput
     */
    providerId?: number;

    /**
     * 供应商名称
     *
     * @type {string}
     * @memberof UpdateProductPaperInput
     */
    providerName?: string | null;

    /**
     * 生产商ID
     *
     * @type {number}
     * @memberof UpdateProductPaperInput
     */
    manufacturerId?: number;

    /**
     * 生产商名称
     *
     * @type {string}
     * @memberof UpdateProductPaperInput
     */
    manufacturerName?: string | null;

    /**
     * 库存
     *
     * @type {number}
     * @memberof UpdateProductPaperInput
     */
    count?: number;

    /**
     * 缩写
     *
     * @type {string}
     * @memberof UpdateProductPaperInput
     */
    nameLetter?: string | null;

    /**
     * 英文名称
     *
     * @type {string}
     * @memberof UpdateProductPaperInput
     */
    englishName?: string | null;

    /**
     * 通用名称
     *
     * @type {string}
     * @memberof UpdateProductPaperInput
     */
    commonName?: string | null;

    /**
     * 成本价
     *
     * @type {number}
     * @memberof UpdateProductPaperInput
     */
    costPrice?: number;

    /**
     * 销售价格
     *
     * @type {number}
     * @memberof UpdateProductPaperInput
     */
    salePrice?: number;

    /**
     * 会员价格
     *
     * @type {number}
     * @memberof UpdateProductPaperInput
     */
    memberPrice?: number;

    /**
     * 是否参与打折
     *
     * @type {boolean}
     * @memberof UpdateProductPaperInput
     */
    isDiscount?: boolean;

    /**
     * 是否允许零库存
     *
     * @type {boolean}
     * @memberof UpdateProductPaperInput
     */
    isZeroSale?: boolean;

    /**
     * 可销
     *
     * @type {boolean}
     * @memberof UpdateProductPaperInput
     */
    canSale?: boolean;

    /**
     * 可订
     *
     * @type {boolean}
     * @memberof UpdateProductPaperInput
     */
    canOrder?: boolean;

    /**
     * 出库单位ID
     *
     * @type {number}
     * @memberof UpdateProductPaperInput
     */
    outUnitId?: number;

    /**
     * 出库单位名称
     *
     * @type {string}
     * @memberof UpdateProductPaperInput
     */
    outUnitName?: string | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof UpdateProductPaperInput
     */
    remark?: string | null;

    /**
     * 注意事项
     *
     * @type {string}
     * @memberof UpdateProductPaperInput
     */
    notice?: string | null;

    /**
     * 版本标识
     *
     * @type {string}
     * @memberof UpdateProductPaperInput
     */
    ver?: string | null;

    /**
     * 试纸结果
     *
     * @type {Array<ProductTestStripResults>}
     * @memberof UpdateProductPaperInput
     */
    productTestStripResults?: Array<ProductTestStripResults> | null;

    /**
     * Id
     *
     * @type {number}
     * @memberof UpdateProductPaperInput
     */
    id: number;
}
