/* tslint:disable */
/* eslint-disable */
/**
 * 产品管理
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: liyahui360@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../../base';
import { AddProductProvidersInput } from '../../models/product-manage';
import { AdminResultListProductProvidersOutput } from '../../models/product-manage';
import { AdminResultObject } from '../../models/product-manage';
import { AdminResultProductProviders } from '../../models/product-manage';
import { DeleteProductProvidersInput } from '../../models/product-manage';
import { UpdateProductProvidersInput } from '../../models/product-manage';
/**
 * ProductProvidersApi - axios parameter creator
 * @export
 */
export const ProductProvidersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 增加供应商
         * @param {AddProductProvidersInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProductProvidersAddPost: async (body?: AddProductProvidersInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/productProviders/add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 删除供应商
         * @param {DeleteProductProvidersInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProductProvidersDeleteDelete: async (body?: DeleteProductProvidersInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/productProviders/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取供应商
         * @param {number} id 主键Id
         * @param {Date} [createTime] 创建时间
         * @param {Date} [updateTime] 更新时间
         * @param {number} [createUserId] 创建者Id
         * @param {number} [updateUserId] 修改者Id
         * @param {boolean} [isDelete] 软删除
         * @param {string} [ver] 版本标识
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProductProvidersDetailGet: async (id: number, createTime?: Date, updateTime?: Date, createUserId?: number, updateUserId?: number, isDelete?: boolean, ver?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiProductProvidersDetailGet.');
            }
            const localVarPath = `/api/productProviders/detail`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (id !== undefined) {
                localVarQueryParameter['Id'] = id;
            }

            if (createTime !== undefined) {
                localVarQueryParameter['CreateTime'] = (createTime as any instanceof Date) ?
                    (createTime as any).toISOString() :
                    createTime;
            }

            if (updateTime !== undefined) {
                localVarQueryParameter['UpdateTime'] = (updateTime as any instanceof Date) ?
                    (updateTime as any).toISOString() :
                    updateTime;
            }

            if (createUserId !== undefined) {
                localVarQueryParameter['CreateUserId'] = createUserId;
            }

            if (updateUserId !== undefined) {
                localVarQueryParameter['UpdateUserId'] = updateUserId;
            }

            if (isDelete !== undefined) {
                localVarQueryParameter['IsDelete'] = isDelete;
            }

            if (ver !== undefined) {
                localVarQueryParameter['Ver'] = ver;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新供应商
         * @param {UpdateProductProvidersInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProductProvidersEditPut: async (body?: UpdateProductProvidersInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/productProviders/edit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取供应商列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProductProvidersListPost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/productProviders/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 分页查询供应商
         * @param {AddProductProvidersInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProductProvidersPagePost: async (body?: AddProductProvidersInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/productProviders/page`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取供应商列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProductProvidersSelectListPost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/productProviders/selectList`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProductProvidersApi - functional programming interface
 * @export
 */
export const ProductProvidersApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 增加供应商
         * @param {AddProductProvidersInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductProvidersAddPost(body?: AddProductProvidersInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ProductProvidersApiAxiosParamCreator(configuration).apiProductProvidersAddPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 删除供应商
         * @param {DeleteProductProvidersInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductProvidersDeleteDelete(body?: DeleteProductProvidersInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ProductProvidersApiAxiosParamCreator(configuration).apiProductProvidersDeleteDelete(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取供应商
         * @param {number} id 主键Id
         * @param {Date} [createTime] 创建时间
         * @param {Date} [updateTime] 更新时间
         * @param {number} [createUserId] 创建者Id
         * @param {number} [updateUserId] 修改者Id
         * @param {boolean} [isDelete] 软删除
         * @param {string} [ver] 版本标识
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductProvidersDetailGet(id: number, createTime?: Date, updateTime?: Date, createUserId?: number, updateUserId?: number, isDelete?: boolean, ver?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultProductProviders>>> {
            const localVarAxiosArgs = await ProductProvidersApiAxiosParamCreator(configuration).apiProductProvidersDetailGet(id, createTime, updateTime, createUserId, updateUserId, isDelete, ver, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 更新供应商
         * @param {UpdateProductProvidersInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductProvidersEditPut(body?: UpdateProductProvidersInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ProductProvidersApiAxiosParamCreator(configuration).apiProductProvidersEditPut(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取供应商列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductProvidersListPost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultObject>>> {
            const localVarAxiosArgs = await ProductProvidersApiAxiosParamCreator(configuration).apiProductProvidersListPost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 分页查询供应商
         * @param {AddProductProvidersInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductProvidersPagePost(body?: AddProductProvidersInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultObject>>> {
            const localVarAxiosArgs = await ProductProvidersApiAxiosParamCreator(configuration).apiProductProvidersPagePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取供应商列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductProvidersSelectListPost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListProductProvidersOutput>>> {
            const localVarAxiosArgs = await ProductProvidersApiAxiosParamCreator(configuration).apiProductProvidersSelectListPost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ProductProvidersApi - factory interface
 * @export
 */
export const ProductProvidersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 增加供应商
         * @param {AddProductProvidersInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductProvidersAddPost(body?: AddProductProvidersInput, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ProductProvidersApiFp(configuration).apiProductProvidersAddPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 删除供应商
         * @param {DeleteProductProvidersInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductProvidersDeleteDelete(body?: DeleteProductProvidersInput, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ProductProvidersApiFp(configuration).apiProductProvidersDeleteDelete(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取供应商
         * @param {number} id 主键Id
         * @param {Date} [createTime] 创建时间
         * @param {Date} [updateTime] 更新时间
         * @param {number} [createUserId] 创建者Id
         * @param {number} [updateUserId] 修改者Id
         * @param {boolean} [isDelete] 软删除
         * @param {string} [ver] 版本标识
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductProvidersDetailGet(id: number, createTime?: Date, updateTime?: Date, createUserId?: number, updateUserId?: number, isDelete?: boolean, ver?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultProductProviders>> {
            return ProductProvidersApiFp(configuration).apiProductProvidersDetailGet(id, createTime, updateTime, createUserId, updateUserId, isDelete, ver, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新供应商
         * @param {UpdateProductProvidersInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductProvidersEditPut(body?: UpdateProductProvidersInput, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ProductProvidersApiFp(configuration).apiProductProvidersEditPut(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取供应商列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductProvidersListPost(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultObject>> {
            return ProductProvidersApiFp(configuration).apiProductProvidersListPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 分页查询供应商
         * @param {AddProductProvidersInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductProvidersPagePost(body?: AddProductProvidersInput, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultObject>> {
            return ProductProvidersApiFp(configuration).apiProductProvidersPagePost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取供应商列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductProvidersSelectListPost(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListProductProvidersOutput>> {
            return ProductProvidersApiFp(configuration).apiProductProvidersSelectListPost(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProductProvidersApi - object-oriented interface
 * @export
 * @class ProductProvidersApi
 * @extends {BaseAPI}
 */
export class ProductProvidersApi extends BaseAPI {
    /**
     * 
     * @summary 增加供应商
     * @param {AddProductProvidersInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductProvidersApi
     */
    public async apiProductProvidersAddPost(body?: AddProductProvidersInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ProductProvidersApiFp(this.configuration).apiProductProvidersAddPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 删除供应商
     * @param {DeleteProductProvidersInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductProvidersApi
     */
    public async apiProductProvidersDeleteDelete(body?: DeleteProductProvidersInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ProductProvidersApiFp(this.configuration).apiProductProvidersDeleteDelete(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取供应商
     * @param {number} id 主键Id
     * @param {Date} [createTime] 创建时间
     * @param {Date} [updateTime] 更新时间
     * @param {number} [createUserId] 创建者Id
     * @param {number} [updateUserId] 修改者Id
     * @param {boolean} [isDelete] 软删除
     * @param {string} [ver] 版本标识
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductProvidersApi
     */
    public async apiProductProvidersDetailGet(id: number, createTime?: Date, updateTime?: Date, createUserId?: number, updateUserId?: number, isDelete?: boolean, ver?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultProductProviders>> {
        return ProductProvidersApiFp(this.configuration).apiProductProvidersDetailGet(id, createTime, updateTime, createUserId, updateUserId, isDelete, ver, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 更新供应商
     * @param {UpdateProductProvidersInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductProvidersApi
     */
    public async apiProductProvidersEditPut(body?: UpdateProductProvidersInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ProductProvidersApiFp(this.configuration).apiProductProvidersEditPut(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取供应商列表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductProvidersApi
     */
    public async apiProductProvidersListPost(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultObject>> {
        return ProductProvidersApiFp(this.configuration).apiProductProvidersListPost(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 分页查询供应商
         * @param {AddProductProvidersInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductProvidersApi
     */
    public async apiProductProvidersPagePost(body?: AddProductProvidersInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultObject>> {
        return ProductProvidersApiFp(this.configuration).apiProductProvidersPagePost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取供应商列表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductProvidersApi
     */
    public async apiProductProvidersSelectListPost(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultListProductProvidersOutput>> {
        return ProductProvidersApiFp(this.configuration).apiProductProvidersSelectListPost(options).then((request) => request(this.axios, this.basePath));
    }
}
