/* tslint:disable */
/* eslint-disable */
/**
 * 数据导出
 * <br/><u><b><font color='FF0000'> 内部接口文档</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 导入药品数据
 *
 * @export
 * @interface ImportDrugsDto
 */
export interface ImportDrugsDto {

    /**
     * 缩写
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    nameLetter?: string | null;

    /**
     * 英文名称
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    englishName?: string | null;

    /**
     * 库存个数
     *
     * @type {number}
     * @memberof ImportDrugsDto
     */
    count?: number;

    /**
     * 成本价
     *
     * @type {number}
     * @memberof ImportDrugsDto
     */
    costPrice?: number;

    /**
     * 编码
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    serialNumber?: string | null;

    /**
     * 名称
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    name: string;

    /**
     * 目录名称
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    firstCategoryName: string;

    /**
     * 目录名称
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    twoCategoryName?: string | null;

    /**
     * 通用名称
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    commonName?: string | null;

    /**
     * 条形码
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    barCode: string;

    /**
     * 供应商名称
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    providerName: string;

    /**
     * 生产商名称
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    manufacturerName: string;

    /**
     * 成分
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    ingredient: string;

    /**
     * 使用方式
     *
     * @type {number}
     * @memberof ImportDrugsDto
     */
    usingMethod: number;

    /**
     * 投药方式
     *
     * @type {number}
     * @memberof ImportDrugsDto
     */
    dosingWay: number;

    /**
     * 有无批次
     *
     * @type {boolean}
     * @memberof ImportDrugsDto
     */
    isAnaesthesia: boolean;

    /**
     * 销售价格
     *
     * @type {number}
     * @memberof ImportDrugsDto
     */
    salePrice: number;

    /**
     * 会员价格
     *
     * @type {number}
     * @memberof ImportDrugsDto
     */
    memberPrice: number;

    /**
     * 是否参与打折
     *
     * @type {boolean}
     * @memberof ImportDrugsDto
     */
    isDiscount: boolean;

    /**
     * 是否允许零库存
     *
     * @type {boolean}
     * @memberof ImportDrugsDto
     */
    isZeroSale: boolean;

    /**
     * 入库单位ID
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    inUnitName: string;

    /**
     * 出库单位名称
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    outUnitName: string;

    /**
     * 入库转换因子
     *
     * @type {number}
     * @memberof ImportDrugsDto
     */
    inSpecific?: number;

    /**
     * 品牌名称
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    brandName?: string | null;

    /**
     * 规格
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    specific?: string | null;

    /**
     * 可销
     *
     * @type {boolean}
     * @memberof ImportDrugsDto
     */
    canSale: boolean;

    /**
     * 可订
     *
     * @type {boolean}
     * @memberof ImportDrugsDto
     */
    canOrder: boolean;

    /**
     * 可盘
     *
     * @type {boolean}
     * @memberof ImportDrugsDto
     */
    canCable: boolean;

    /**
     * 备注
     *
     * @type {string}
     * @memberof ImportDrugsDto
     */
    remark?: string | null;
}
